### PR TITLE
Convert dark theme to SCSS

### PR DESCRIPTION
**Pull request by cromefire**
**Changes**

Convert dark theme (default) to SCSS, for easier maintainability and remixability.

### CODE REVIEW

**Comment by dkanada** [comment]
@cromefire do you want to fix this with the latest changes from master?

**Comment by cromefire** [comment]
Hmm yeah I can try to re do it, maybe without the converter this time, because that was more of a mess than useful I think

**Comment by MrTimscampi** [comment]
I think the proper way to do this would be to figure out what parts are shared between all the themes (even with different values) then make one baseTheme.scss file and use variables for variations, with some theme-specific overrides on some stuff if needed.

**Comment by cromefire** [comment]
Yeah that would be the ideal case but I'm not sure how easy that is...

**Pull request closed without merging**
