### PR TITLE
Fix toggle on tv layout mode 

### PR DESCRIPTION
**Pull request by grafixeyehero**
**To Reproduce**
1. Set a Display Mode 'Tv' on user setting page
2. Go to 'detail page.'
3. Scroll down to 'More Like This'
4. See the toggle

### CODE REVIEW

**Comment by grafixeyehero** [comment]
After

**Comment by joshuaboniface** [comment]
Hey @grafixeyehero for this and all future PRs, please ensure you're providing detailed PR titles, bodies, and commit messages. Even with the after picture I'm having a hard time understanding what this PR does, and so will anyone who looks at it in the Git history in the future.

**Comment by grafixeyehero** [comment]
@joshuaboniface English not my first language. i will try my best to explain for the next time

**Comment by joshuaboniface** [comment]
Thanks @grafixeyehero we don't mind bad English - bad English is better than nothing ;-)

**Pull request merged**
