### PR TITLE
add missing string and translation

### PR DESCRIPTION
**Pull request by s0urcelab**
add missing string in "itemcontextmenu.js"

**Changes**

**Issues**

### CODE REVIEW

**Review by dkanada — APPROVED** [review]

**Comment by dkanada** [comment]
By the way, we have a Weblate instance if you want a more convenient method to edit strings, it doesn't require dealing with GitHub.

**Comment by s0urcelab** [comment]
> By the way, we have a Weblate instance if you want a more convenient method to edit strings, it doesn't require dealing with GitHub.

i tried, but seem like without a origin string(English version) there is no way to add translation.

**Review by anthonylavado — APPROVED** [review]

**Comment by dkanada** [comment]
Hmm that might be an issue then, every string should exist in the source language.

**Comment by anthonylavado** [comment]
Looks like it does exist?
https://github.com/jellyfin/jellyfin-web/blob/e108997376ef75d999398599ce0bec844afcbbcc/src/strings/en-us.json#L1002

**Pull request merged**
