### PR TITLE
Fix details position while poster is loading

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Pushes the content of the details page to their proper position while the poster loads, to prevent having them slide over.

**Issues**

I'm pretty sure there was an issue for this, but I'm not able to find it.

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Before

image

After

image

**Comment by dmitrylyzo** [comment]
There will be a gap between card and progressbar if you have video with extracted image (for example, TV show episode).
progress-gap

I have some fix for placeholder cards (no poster) but stuck with WebOS 2: `float` (card) doesn't like `absolute` (progressbar) - page layout is messed up.

**Comment by JustAMan** [comment]
@MrTimscampi why close?

**Comment by Nickbert7** [comment]
> I'm pretty sure there was an issue for this, but I'm not able to find it.

Should be my issue https://github.com/jellyfin/jellyfin-web/issues/928

**Comment by MrTimscampi** [comment]
> @MrTimscampi why close?

@JustAMan It's fixed in a better way as part of #1206 

@Nickbert7 Thanks :) I'll tag it in the other PR.

**Pull request closed without merging**
