### PR TITLE
Quick fix Now playing bar controls

### PR DESCRIPTION
**Pull request by grafixeyehero**
**Issues**
Now playing bar controls not working #431

### CODE REVIEW

**Comment by cvium** [comment]
Could you elaborate on why you removed the flex-grow?

**Comment by grafixeyehero** [comment]
> Could you elaborate on why you removed the flex-grow?
`.nowPlayingBarRight` take 60% of the screen and `.nowPlayingBarInfoContainer` take 40% of the screen. when we add a flex-grow in `.nowPlayingBarRight` It dictates what amount of the available space inside the flex container the item should take the space. so the `.nowPlayingBarRight` cover the `.nowPlayingBarCenter `

**Comment by grafixeyehero** [comment]
Before


After

**Comment by cvium** [comment]
Shouldn't we remove flex-grow from the other two as well?

**Comment by grafixeyehero** [comment]
> 
> 
> Shouldn't we remove flex-grow from the other two as well?

which one?

**Pull request merged**
