### PR TITLE
Redesign item details screen for mobile

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**

* Redesigns the item details screen on mobile.
* Removes css prefixes that should be added by autoprefixer.

| Screen | This PR | 10.7 | 10.6 |
|-|-|-|-|
| Movie Portrait | Screen Shot 2021-08-13 at 14 31 23 | Screen Shot 2020-12-18 at 10 06 56 | Screen Shot 2020-12-18 at 10 07 00 |
| Movie Landscape | Screen Shot 2021-08-13 at 14 33 02 | Screen Shot 2020-12-18 at 10 07 33 | Screen Shot 2020-12-18 at 10 07 42 |
| Actor Portrait | Screen Shot 2021-08-13 at 14 34 13 | Screen Shot 2020-12-18 at 10 08 02 | Screen Shot 2020-12-18 at 10 19 14 |
| Album Portrait | Screen Shot 2021-08-13 at 14 35 06 | Screen Shot 2020-12-18 at 10 08 41 | Screen Shot 2020-12-18 at 10 08 43 |
| Album Landscape | Screen Shot 2021-08-13 at 14 36 20 | Screen Shot 2020-12-18 at 13 19 03 | Screen Shot 2020-12-18 at 13 18 59 |

**Issues**
N/A

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
The screenshots use the dark theme but the corners of the poster are rounded while all other elements in the dark theme currently have square corners.

**Comment by thornbill** [comment]
Rounded corners on cards were added in unstable recently. This latest iteration of the mobile layout is using the standard card element, so that is inherited along with working blurhashes. :tada:

**Comment by thornbill** [comment]
@dmitrylyzo I adjusted the overflow rules a bit so it only affects the `h1` and not the `div` behind it. Can you verify if this fixes that issue? Thanks!

**Comment by dmitrylyzo** [comment]
> @dmitrylyzo I adjusted the overflow rules a bit so it only affects the `h1` and not the `div` behind it. Can you verify if this fixes that issue? Thanks!

Yes, it works. As an alternative to this, we can remove `infoText` class from `infoWrapper` and add `min-width: 0;` to `infoWrapper` class (to make the info block shrinkable).

**Review by joshuaboniface — APPROVED** [review]

**Review by dmitrylyzo — APPROVED** [review]
By "alternative" I meant "instead of your previous commit" :sweat_smile:
Anyway, it works.

**Comment by thornbill** [comment]
Thought I would do both just to be sure... 🤣

**Pull request merged**
