### PR TITLE
Small now playing page redesign

### PR DESCRIPTION
**Pull request by Camc314**
Some small changes to the nowPlaying page

**Changes**
<details>
<summary>
Old view (phone)
</summary>

2020-08-27-now-playing-iphone-old

</details>

<details>
<summary>
New view (phone)
</summary>

2020-08-27-now-playing-iphone-new

</details>

<details>
<summary>
Old view (tablet/desktop)
</summary>

2020-08-27-now-playing-ipad-old

</details>

<details>
<summary>
New view (tablet/desktop)
</summary>

2020-08-27-now-playing-ipad-new

</details>

### CODE REVIEW

**Comment by neopc10** [comment]
I think the desktop view is a step in the right direction. 

I'm not at all big on the mobile view-- I think it's going back to what was present pre-10.6. I'd much rather see far less padding and blank space. I would instead move the media controls up to just below the seekbar and expose the play queue.

Ideally, the play queue would appear under the media controls in your desktop view as well (see Qobuz/Tidal).

**Comment by MattSpec** [comment]
I like both of the new designs. Exposing the play queue on the desktop/tablet view would be a welcome change. It could make some use of the blank space and would make for a great experience when playing music on my tablet/tv.

For mobile. I am a fan of what you've put together here. For me its more natural to have the player controls closer to the bottom of the screen. It also makes the album art more of the focal point and its much more aesthetically pleasing. I certainly don't agree with exposing queue on mobile. That was the previous design and just was cleaned up.

**Comment by neopc10** [comment]
It was cleaned up because it was very poorly implemented. See something along the lines of what Gelli uses.

**Comment by dkanada** [comment]
Once we migrate to Vue, I expect completely separate layouts for the desktop and mobile views here, similar to the PR currently open for a TV specific home layout.

**Pull request closed without merging**
