### PR TITLE
[WIP] Add loading placeholders to cards - Part 1

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Adds a loading placeholder to cards. Icon is SVG to be scalable.

image

image

image

Some cards don't have a perfectly centered icon and need a bit more refactoring, but this is a nice start.

**Issues**

None

### CODE REVIEW

**Comment by dkanada** [comment]
I think we should match the media type cards used in other sections.

**Comment by KristupasSavickas** [comment]
How does this work with your endless scroll PR?

**Comment by ferferga** [comment]
@dkanada I completely disagree with you. With the Jellyfin icon, you can distinguish quickly if the item has an image (but hasn't loaded yet) between items that don't have an image at all.

@MrTimscampi Why is this WIP btw? I tried it back in the day you published it, but I remember seeing it pretty finished.

@KristupasSavickas That PR only changes the amount of items that will be displayed on screen. Images still would need to be downloaded from the server.

**Comment by KristupasSavickas** [comment]
@ferferga Yeah, I get that, what I wondered was if library scrolling was faster, i.e. cards with placeholder graphics were loaded before images were as you kept scrolling.

**Comment by dmitrylyzo** [comment]
> I completely disagree with you. With the Jellyfin icon, you can distinguish quickly if the item has an image (but hasn't loaded yet) between items that don't have an image at all.

I think @dkanada means darkened version of media type icon.
test1
_there is already a marker on the photo item_

test2

**Comment by MrTimscampi** [comment]
> @MrTimscampi Why is this WIP btw? I tried it back in the day you published it, but I remember seeing it pretty finished.

There's a few cases where it looks wrong and I haven't taken the time to go back to it.

> what I wondered was if library scrolling was faster, i.e. cards with placeholder graphics were loaded before images were as you kept scrolling.

This is already the case currently. Only the visible images will load when a library is shown. As you scroll, more will load as they get into view.  
The big issue currently is that images won't unload when they leave the viewport. The PR to add limit setting (that enables you to load the full library if set to 0) will work the same way in that regard, for now. The team as a whole wants to improve the image loader, though, but no one has gotten to it at the moment.

> I think @dkanada meant darkened version of media type icon.

That does look really good.

**Comment by dkanada** [comment]
I didn't mean that but I like your idea better, so let's roll with it!

**Comment by ferferga** [comment]
@dmitrylyzo I like yours more than the original idea. You're still able to distinguish items that aren't fully loaded while also being able to know the type of their item, Both things at once!

I vote for it as well :)

**Comment by MrTimscampi** [comment]
After looking a bit into this, there's a simple-ish way to do it, but it required more refactoring to the card building code than I'm willing to do right now. And with the large refactoring planned, it's probably not the best to spend time rewriting the card builder...

Here's what it'd look like with the current code:

image

**Pull request closed without merging**
