### PR TITLE
Replace equalizer.gif with equalizer.svg

### PR DESCRIPTION
**Pull request by SethFalco**
**Changes**

I made an SVG version of the GIF.
I've tried to keep this as close to the GIF as possible, so they should be near identical.

There are 2 benefits:
* The file size is smaller.
* The animation is **_much_** smoother.

| Type | Size |
|---|---
| GIF | 2.6 KB (2,621 bytes)
| SVG | 1.5 KB (1,541 bytes)

You can see them side-by-side here:
https://codepen.io/SethFalco/pen/LYzOpJv

**Issues**
* Related to https://github.com/jellyfin/jellyfin-web/issues/2792

---

I realize this is a very minor optimization, but this was mostly because I was curious if I could make a nice equalizer vector, tbh.

You're welcome to point out anything you'd like changed about it. It should be pretty easy since it's just a vector now anyway.

As a side-note, you don't want to run `equalizer.svg` through [svgo](https://github.com/svg/svgo). The project has a bug that removes the `to` key frames, which screws up the animation. I've already optimized the SVG with it, then manually fixed that issue.

### CODE REVIEW

**Comment by thornbill** [comment]
While this seems like a positive change overall, it will require some testing to verify it works on some of the older browsers shipped to TVs (webOS and Tizen).

**Comment by SethFalco** [comment]
Sounds fair, I've only tested in on Chromium and Firefox for now.
Do you (or someone else on the team) have the means to test them, or will I have to arrange that?

I can test it on the browser on my Samsung TV (Tizen) and report the results, meanwhile.

If you find that it doesn't work somewhere, feel free to just let me know and I can check if there's another way I can achieve the same thing.

**Comment by SethFalco** [comment]
Just a follow-up, so I tested in on my Samsung TV in the default browser, and it worked as expected.

Name: UE40NU7122
Product: https://www.samsung.com/uk/support/model/UE40NU7120KXXU/
OS Version: 1320

**Comment by SethFalco** [comment]
Very minor change that shaves off 2.22% bytes (35 bytes) from the original SVG using [CSSO](https://github.com/css/csso).

Just learned that for CSS properties that take multiple parameters, there's no need for whitespace if the previous parameter ends with a unit.

For example:
```css
clip-path:inset(84% 0 0)
```

Can be written as:
```css
clip-path:inset(84%0 0)
```

**Comment by thornbill** [comment]
I believe @dmitrylyzo tested this on webOS and reported that it was not working on some versions there.

**Comment by SethFalco** [comment]
RIP. I'm a bit surprised at that, though. 🤔 
Would it be possible to get a GIF of what they saw?

**Comment by dmitrylyzo** [comment]
> RIP. I'm a bit surprised at that, though. thinking Would it be possible to get a GIF of what they saw?
> 
> As in, I'd like to know more. Did it show the first frame only? Was the animation just broken? Did anything render at all?

I tested in the emulator. webOS 1/2 uses the old WebKit web engine, and there was no animation at all.
webos-1
_In the Chrome DevTools, I see the animation._

I tried changing `fill` in the keyframes, but it doesn't work as well.

**Comment by SethFalco** [comment]
I'm actually having some trouble with this, so have decided to shelve it.
A bit unfortunate, but RIP.

Seems my initial approach doesn't have enough browser compatibility, and the approach with `scaleY` is yielding expected results for my locally. :thinking:

**Pull request closed without merging**
