### PR TITLE
Fix icon doubling

### PR DESCRIPTION
**Pull request by dmitrylyzo**
**WARNING about recording button**
This is blindly fixed. I checked that there is no more doubling.

**Changes**
* Fix recording button.
* Fix brightness indicator (OSD).
* Fix sort button.

**Issue**
recordingbutton-1

### CODE REVIEW

**Comment by Nickbert7** [comment]
Screenshot_20200307-143121_Chrome
In the photo library it seems to be the same

**Comment by dmitrylyzo** [comment]
Brightness OSD is also doubled.

**Comment by dmitrylyzo** [comment]
Probably, `itemstab.js` also has doubled sort, but it seems like it is not used :confused:

And now that I'm done, I think we could just create icon dictionary (`name` -> `hex`) and drop that classList manipulation.

**Comment by Nickbert7** [comment]
Sometimes in the tasks page I also get the doubled icons after a task has finished

**Pull request merged**
