### PR TITLE
Implement frontend component of max user sessions

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
Adds the frontend component of https://github.com/jellyfin/jellyfin/pull/4269

**Issues**
Implements Fider #59

### CODE REVIEW

**Review by Camc314 — APPROVED** [review]
LGTM

**Review by barronpm — APPROVED** [review]

**Comment by mairajha** [comment]
how can I use that code in my jellyfin setup? I am on windows portable build of jellyfin - any guide would be highly appreciated please!

**Comment by Camc314** [comment]
In the unstable build, there are user settings where you can edit the max number of user sessions.

The next release should be out shortly^{tm} . Unstable may be buggy and have issues if you decide to use it.

**Comment by mairajha** [comment]
Is that available in unstable build for windows (the combined one) portable installation

**Comment by nyanmisaka** [comment]
image

**Comment by mairajha** [comment]
Tried unstable portable version for windows but when running jellyfin.exe it stuck at one time & nothing happens

**Comment by tony678933** [comment]
Hi, I wanted to know if this feature is intended to reflect the total number of streams being used at the same time, or if it represents the total number of sign-in devices for the user.

I'm currently facing an issue in which I cannot login to my android app due to the log in my docker container stating 
**[04:16:03] [ERR] [156] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: [{local IP}] User is at their maximum number of sessions. URL POST /Users/authenticatebyname**

I am getting this error even though I am only viewing on 1 device at a time and the setting is set to 3 simultaneously.

**Comment by joshuaboniface** [comment]
@tony678933 It is based on logged in sessions. So 3 sessions on different apps, or (somehow) 3 sessions as the user on one app. It was implemented this way since, for practical purposes, one session can only ever play one thing at a time. The downside of course is that idle sessions count.

**Pull request merged**
