### PR TITLE
Next episode has mismatched language between server and ui (rebased)

### PR DESCRIPTION
**Pull request by Kinsteen**
Simple rebase on new master to remove merge conflicts of #4852. Didn't test yet, would be happy if people could!

> **Root cause**
> 
> The autoset options only seem to take effect on non-transcoded media-- the transcode URL is never updated! This means that if the selected audio does not match the default, the audio/subs are in the default but the UI reflects the auto-set variant (showing a language that isn't playing).
> 
> **Changes**
> 
> When setting the track in the the auto-set logic, also trivially change the audio index in the transcode URL to match.
> 
> This fixes it in most cases, but there may be some edge cases that need to go through the full validation to recreate the URL. I don't know the code well enough for that, though.
> 
> **Issues**
> 
> Fixes https://github.com/jellyfin/jellyfin-web/issues/3994

### CODE REVIEW

**Comment by viown** [comment]
Was able to reproduce the mentioned issue, and after testing this, it does seem to fix it.

**Comment by dmitrylyzo** [comment]
_In addition to https://github.com/jellyfin/jellyfin-web/pull/4852#issuecomment-2118867286_

Changing streams after receiving PlaybackInfo may result in unwanted remuxing/transcoding:
- The "best" subtitles may not require transcoding.
- The "best" audio may not require remuxing. _<- less possible_

It's better to do this on the server side so that every client gets this auto-select feature.

But speaking of web, we should do ranking and update corresponding fields before getting PlaybackInfo:
https://github.com/jellyfin/jellyfin-web/blob/f4a872d78073823ba6102d9fc5245804d18e26d6/src/components/playback/playbackmanager.js#L2577-L2578

**Comment by viown** [comment]
> _In addition to [#4852 (comment)](https://github.com/jellyfin/jellyfin-web/pull/4852#issuecomment-2118867286)_
> 
> Changing streams after receiving PlaybackInfo may result in unwanted remuxing/transcoding:
> 
>     * The "best" subtitles may not require transcoding.
> 
>     * The "best" audio may not require remuxing. _<- less possible_
> 
> 
> It's better to do this on the server side so that every client gets this auto-select feature.
> 
> But speaking of web, we should do ranking and update corresponding fields before getting PlaybackInfo:
> 
> https://github.com/jellyfin/jellyfin-web/blob/f4a872d78073823ba6102d9fc5245804d18e26d6/src/components/playback/playbackmanager.js#L2577-L2578

Setting the audioStreamIndex/subtitleStreamIndex in options does not seem to affect the stream URL in some scenarios (only when remuxing/direct playing). Any idea why that is?

**Comment by dmitrylyzo** [comment]
> Setting the audioStreamIndex/subtitleStreamIndex in options does not seem to affect the stream URL in some scenarios (only when remuxing/direct playing). Any idea why that is?

Because they are processed on the client side when DirectPlay. It should use `DefaultAudioStreamIndex` and `DefaultSubtitleStreamIndex`.

**Comment by Kinsteen** [comment]
Seems so, closing

**Pull request closed without merging**
