### PR TITLE
Fix CSS linting errors

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

In preparation for automated CSS linting, this PR aims to fix all the errors in the current CSS, while being as conservative as possible.

This is a pretty massive PR, but most of what it does it move stuff around the files to respect rules, change indentation and case of some things.

**Issues**

None

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Please wait before merging as some stuff is still left to fix:

```
src/components/emby-slider/emby-slider.css
 1:1  ✖  Unexpected unknown type selector "_"   selector-type-no-unknown

src/components/htmlvideoplayer/style.css
 38:17  ✖  Unexpected unknown pseudo-element selector "::cue"   selector-pseudo-element-no-unknown

src/components/remotecontrol/remotecontrol.css
 76:3  ✖  Unexpected unknown property "user-drag"   property-no-unknown

src/components/upnextdialog/upnextdialog.css
 67:3  ✖  Unexpected unknown property "user-drag"   property-no-unknown

src/css/material-icons/style.css
 9:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword

src/css/videoosd.css
 173:3  ✖  Unexpected unknown property "user-drag"   property-no-unknown
```

**Comment by dkanada** [comment]
Can we start with four spaces for now to make reviewing easier?

**Comment by dkanada** [comment]
Also, we should wait until the vendor prefixes get removed since that will change this pull request drastically.

**Comment by MrTimscampi** [comment]
For sure, it's easy to rebase stuff if need be (the first commit is automatic, so it's simply a matter of relaunching the command and rebasing the rest of the PR).

I'll switch the rules to 4 spaces and we'll work on merging the autoprefix stuff before this :)

**Comment by MrTimscampi** [comment]
@dkanada I rebased this on the most recent CSS, since the vendor prefixes are merged.

Do note that this also fixes the text in homeLibraryButton to not be vertically centered by adding a 0.30em top margin to the text element inside of it. See screenshots below.

Before:
image

After:
image

**Comment by JustAMan** [comment]
@MrTimscampi you have **a lot** of merge conflicts, pls fix :)

**Comment by dkanada** [comment]
He was working on the webpack build first, this was put on hold for a while.

**Pull request closed without merging**
