### PR TITLE
fix: use navigate instead of resolver

### PR DESCRIPTION
**Pull request by ilteoood**
**Changes**
In the routes, use the `Navigate` element instead of redirect resolver

**Issues**
Fixes https://github.com/jellyfin/jellyfin-tizen/issues/279

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
FYI, we backport from the release branch to `master`, so other PR may be closed.

Does this fix the Tizen issue? I mean, have you tested this?

**Comment by ilteoood** [comment]
Yes, yesterday before opening the pr. My patched version is the one I'm running on the tv now.

**Comment by thornbill** [comment]
I'm curious what is the underlying issue with using `redirect`? Is it using something internally that we fail to polyfill?

**Comment by ilteoood** [comment]
> I'm curious what is the underlying issue with using `redirect`? Is it using something internally that we fail to polyfill?

It seems to be an odd internal behavior of the router: on tizen, instead of looking for the resolver, it checks just for the `element` property and then throws the error.
Additionally, looking at the [official documentation](https://reactrouter.com/en/main/fetch/redirect) seems that redirect should be used when handling http calls. In other scenarios, the `Navigate` is the way to go

**Comment by ilteoood** [comment]
I don't think so, this is more a library specific implementation rather than issue with the js engine itself

**Comment by ilteoood** [comment]
Here is the piece of code that is triggering it: https://github.com/remix-run/react-router/blob/0f2b167e9b862d5e6b3425438787c8e7b39197f4/packages/react-router/lib/hooks.tsx#L450

**Comment by ilteoood** [comment]
Hi @thornbill, is this ready to he merged or do I need to do something more?

**Comment by ilteoood** [comment]
Ping @thornbill

**Comment by thornbill** [comment]
You really haven't explained why this is an issue for Tizen. The code you link to appears to only print a developer warning and looking at the message

> This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.

it describes the behavior we _want_ to happen. Also if you look at the react-router examples, you can see they have an [authentication example](https://github.com/remix-run/react-router/blob/dev/examples/auth-router-provider/src/App.tsx) that our code is based on (a `loader` returning a `redirect`).

**Comment by ilteoood** [comment]
The issue is explained in the original issue https://github.com/jellyfin/jellyfin-tizen/issues/279.
It is an issue because it doesn't load the login screen.
Additionally, on the exaple you pasted I don't see a redirect but just an empty object instead of an http call. In fact, according to the official doc, it should be used to provide data to the route: https://reactrouter.com/en/main/route/loader, which is not our scenario.

**Comment by thornbill** [comment]
My question is why is this only an issue for Tizen. If the problem was that react router doesn't support what we are doing for with the redirect then it wouldn't work anywhere.

**Comment by ilteoood** [comment]
Honestly speaking I don't know. The Tizen version I'm using is very old and the peculiarity of its engine implementation could have some bugs that can be hardly reproduced elsewhere. This would not be a new thing, since even in this repo there are some patches just for this platform.

**Comment by ilteoood** [comment]
BTW, are we seriously spending weeks discussing on a PR of 2 lines of code (repeated 2 times), that changes stuff following the library's best practice?
Version 10.9.9 has been released today and I'll need to manually patch it again to make it work on my TV.

**Comment by ilteoood** [comment]
Looking it a bit deeper it could be that my tizen version doesn't fully support the header or the response classes to do redirects.
Here is the implementation I checked: https://github.com/remix-run/react-router/blob/55c18bfc8e20417204cce5ecda88fe03520ad257/packages/router/utils.ts#L1615

I'm supposing it because jellyfin already has a patch for the headers constructor for tizen. Unfortunately I'm not 100 sure about it because for my tizen version there isn't any emulator and test each time on the TV is extremely painful.

**Comment by ilteoood** [comment]
Another user has the same issue: https://github.com/jellyfin/jellyfin-tizen/issues/279#issuecomment-2282197307

Can we consider merging this?

**Review by thornbill — APPROVED** [review]

**Pull request merged**
