### PR TITLE
Fix variable reference

### LINKED ISSUE #852: [10.5-dev] Playback Settings icon (gear icon?) missing from player screen
**Describe the bug**

When playing a video, the Playback Settings (gear) icon is no longer present.

**To Reproduce**

1. Go to 'Movies'
2. Click on a movie to play it
3. Observer player controls are missing the Playback Settings icon

**Expected behavior**

Gear Icon is present and available to change quality or view playback data

**Logs**

```js
GEThttps://jftest2.example.com/Items/2b761a2d19d7a0cb472d19bc932733ca/Images/Backdrop?quality=100&tag=cf7f96c4ab66e733e3284d0cc6eb42de
[HTTP/2 200 OK 31ms]

playing url: https://jftest2.example.com/Videos/2b734a2d19d7a0cb472d19bc932733ca/stream.mp4?Static=true&mediaSourceId=2b761a2d19d7a0cb472d19bc932733ca&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzAuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83MC4wfDE1NzU0MDU2MTc3Mjk1&api_key=93bbecb69bfc46d08054bf70ab4d3329&Tag=5365dec4a6909cbb3dcd3d9f74d49ac7 plugin.js:502:21
GEThttps://jftest2.example.com/Videos/2b734a2d19d7a0cb472d19bc932733ca/stream.mp4?Static=true&mediaSourceId=2b761a2d19d7a0cb472d19bc932733ca&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzAuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83MC4wfDE1NzU0MDU2MTc3Mjk1&api_key=93bbecb69bfc46d08054bf70ab4d3329&Tag=5365dec4a6909cbb3dcd3d9f74d49ac7

appRouter - processing path request /web#!/videoosd.html appRouter.js:390:17
appRouter - user is authenticated appRouter.js:411:21
appRouter - proceeding to /web#!/videoosd.html appRouter.js:428:17
Active player: {"name":"Html Video Player","id":"htmlvideoplayer","playerName":"Html Video Player","playableMediaTypes":[false,true,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","PlayMediaSource","PlayTrailers","ToggleFullscreen","SetBrightness","SetAspectRatio"]} playbackmanager.js:1027:25

ReferenceError: e is not defined
^^^^ this might be it?

nowplayingbar.js:665:9
GEThttps://jftest2.example.com/web/controllers/playback/videoosd.js?v=10.5.0
[HTTP/2 200 OK 11ms]

GEThttps://jftest2.example.com/web/components/scrollhelper.js?v=10.5.0
[HTTP/2 200 OK 5ms]

GEThttps://jftest2.example.com/web/assets/css/videoosd.css?v=10.5.0
[HTTP/2 200 OK 5ms]

XHRGEThttps://jftest2.example.com/web/videoosd.html?v=10.5.0&r=0
[HTTP/2 200 OK 20ms]

setting new text track index to: -1 plugin.js:1331:21
GEThttps://jftest2.example.com/web/components/subtitlesync/subtitlesync.js?v=10.5.0
[HTTP/2 200 OK 105ms]

XHRGEThttps://jftest2.example.com/web/components/subtitlesync/subtitlesync.template.html?v=10.5.0&r=0
[HTTP/2 200 OK 80ms]

GEThttps://jftest2.example.com/web/components/subtitlesync/subtitlesync.css?v=10.5.0
```

**Screenshots**

image

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.5-dev

**Additional context**
Pretty sure this worked yesterday.

### LINKED ISSUE #853: [10.5-dev] Video continues playing in background after back button
**Describe the bug**

When viewing a video, then hitting the back button (or pause, then back button), the video continues to play behind the other on-screen elements (as if it were a background image).

**To Reproduce**

1. Go to Movies
2. Click on the play button inside a movie cover
3. Wait for movie to begin playing, osd to appear
4. Hit back button
5. Observe movie is still playing behind the movie listings/covers

**Expected behavior**

Movie is stopped, and regular background is shown behind movie listing

**Logs**

```js
appRouter - processing path request /web#!/movies.html appRouter.js:390:17
appRouter - user is authenticated appRouter.js:411:21
appRouter - proceeding to /web#!/movies.html appRouter.js:428:17
No available track, cannot apply offset:  0 plugin.js:611:29
Found backdrop id list in cache. Key: backdrops2_65334ef7bcf14db6a1b6446c558402c8movief137a2dd21bbc1b99aa5c0f6bf02a805 autobackdrops.js:13:21
ReferenceError: e is not defined
nowplayingbar.js:665:9
TypeError: playerData.streamInfo is undefined
playbackmanager.js:1070:17
appRouter - processing path request /web#!/home.html appRouter.js:390:17
appRouter - user is authenticated appRouter.js:411:21
appRouter - proceeding to /web#!/home.html appRouter.js:428:17
GEThttps://jftest2.example.com/web/controllers/home.js?v=10.5.0
[HTTP/2 200 OK 16ms]

GEThttps://jftest2.example.com/web/components/tabbedview/tabbedview.js?v=10.5.0
[HTTP/2 200 OK 0ms]

XHRGEThttps://jftest2.example.com/web/home.html?v=10.5.0&r=0
[HTTP/2 200 OK 0ms]

GEThttps://jftest2.example.com/web/assets/img/banner-light.png
[HTTP/2 200 OK 16ms]

Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items?SortBy=IsFavoriteOrLiked%2CRandom&Limit=20&Recursive=true&IncludeItemTypes=movie%2Cseries%2Cbook&ImageTypes=Backdrop&EnableTotalRecordCount=false apiclientcore.js:285:21
XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items?SortBy=IsFavoriteOrLiked%2CRandom&Limit=20&Recursive=true&IncludeItemTypes=movie%2Cseries%2Cbook&ImageTypes=Backdrop&EnableTotalRecordCount=false
[HTTP/2 200 OK 15ms]

GEThttps://jftest2.example.com/web/controllers/hometab.js?v=10.5.0
[HTTP/2 200 OK 15ms]

GEThttps://jftest2.example.com/web/components/homesections/homesections.js?v=10.5.0
[HTTP/2 200 OK 16ms]

TypeError: playerData.streamInfo is undefined
playbackmanager.js:1070:17
GEThttps://jftest2.example.com/web/components/homesections/homesections.css?v=10.5.0
[HTTP/2 200 OK 0ms]

Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Views apiclientcore.js:285:21
XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Views
[HTTP/2 200 OK 17ms]

Requesting url without automatic networking: https://jftest2.example.com/LiveTv/Programs/Recommended?userId=65334ef7bcf14db6a1b6446c558402c8&IsAiring=true&limit=1&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio apiclientcore.js:285:21
XHRGEThttps://jftest2.example.com/LiveTv/Programs/Recommended?userId=65334ef7bcf14db6a1b6446c558402c8&IsAiring=true&limit=1&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio
[HTTP/2 200 OK 16ms]

GEThttps://jftest2.example.com/web/components/emby-itemrefreshindicator/emby-itemrefreshindicator.js?v=10.5.0
[HTTP/2 200 OK 0ms]

GEThttps://jftest2.example.com/web/components/emby-scrollbuttons/emby-scrollbuttons.js?v=10.5.0
[HTTP/2 200 OK 17ms]

GEThttps://jftest2.example.com/Items/f137a2dd21bbc1b99aa5c0f6bf02a805/Images/Primary?tag=c8b11d000a04c8e5370ab44254f8d882&quality=90
[HTTP/2 200 OK 104ms]

GEThttps://jftest2.example.com/Items/69e88d4e1462d56fb23d93d8a312d597/Images/Primary?tag=46007595ef415117b934bca717839925&quality=90
[HTTP/2 200 OK 33ms]

GEThttps://jftest2.example.com/web/elements/emby-progressring/emby-progressring.js?v=10.5.0
[HTTP/2 200 OK 0ms]

Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video apiclientcore.js:285:21
Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio apiclientcore.js:285:21
Requesting url without automatic networking: https://jftest2.example.com/LiveTv/Programs/Recommended?userId=65334ef7bcf14db6a1b6446c558402c8&IsAiring=true&limit=24&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio apiclientcore.js:285:21
Requesting url without automatic networking: https://jftest2.example.com/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo&UserId=65334ef7bcf14db6a1b6446c558402c8&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false apiclientcore.js:285:21
Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 apiclientcore.js:285:21
Requesting url without automatic networking: https://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=69e88d4e1462d56fb23d93d8a312d597 apiclientcore.js:285:21
XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
[HTTP/2 200 OK 38ms]

XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
[HTTP/2 200 OK 38ms]

XHRGEThttps://jftest2.example.com/LiveTv/Programs/Recommended?userId=65334ef7bcf14db6a1b6446c558402c8&IsAiring=true&limit=24&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio
[HTTP/2 200 OK 53ms]

XHRGEThttps://jftest2.example.com/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo&UserId=65334ef7bcf14db6a1b6446c558402c8&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false
[HTTP/2 200 OK 22ms]

XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805
[HTTP/2 200 OK 38ms]

XHRGEThttps://jftest2.example.com/Users/65334ef7bcf14db6a1b6446c558402c8/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=69e88d4e1462d56fb23d93d8a312d597
[HTTP/2 200 OK 1303ms]

GEThttps://jftest2.example.com/web/elements/emby-progressring/emby-progressring.css?v=10.5.0
[HTTP/2 200 OK 22ms]

GEThttps://jftest2.example.com/web/components/emby-scrollbuttons/emby-scrollbuttons.css?v=10.5.0
[HTTP/2 200 OK 38ms]

GEThttps://jftest2.example.com/web/6d1baa4104fc303c312def13f9cf7d12.woff2
[HTTP/2 200 OK 38ms]

XHRGEThttps://jftest2.example.com/web/elements/emby-progressring/emby-progressring.template.html?v=10.5.0&r=0
[HTTP/2 200 OK 0ms]

GEThttps://jftest2.example.com/Items/79dc1953265025b9fe907ea34e03e4ec/Images/Backdrop?tag=a344ce975d0a5627b232054b734e3219&quality=80
[HTTP/2 200 OK 47ms]

GEThttps://jftest2.example.com/Items/f51b9446aba8471b4083f6e448ce3056/Images/Primary?tag=2029f42ac6061eab9da940e7ee311437&quality=90
[HTTP/2 200 OK 0ms]

GEThttps://jftest2.example.com/Items/6f68520c52b853fc97d606f840c2358e/Images/Primary?tag=10b3aaabef22b1c3ac2d9c73c827f498&quality=90
[HTTP/2 200 OK 15ms]

GEThttps://jftest2.example.com/Items/d71604104da3a1fc4af09ba8d59031ba/Images/Primary?tag=10b3aaabef22b1c3ac2d9c73c827f498&quality=90
[HTTP/2 200 OK 15ms]

GEThttps://jftest2.example.com/Items/8f5898a058785bb117e433caf151da42/Images/Primary?tag=401e9f41c63ac8dafdd54813a5c15308&quality=90
[HTTP/2 200 OK 648ms]

GEThttps://jftest2.example.com/Items/768bc7cfda473200bc56e3c688159c60/Images/Primary?tag=d0a96432efdd389671e68e42ddbc46b4&quality=90
[HTTP/2 200 OK 717ms]

GEThttps://jftest2.example.com/Items/ab7a1b577c6363688b499112460f9789/Images/Primary?tag=cf4a11fdd75764a8e698948cdcdbc6c2&quality=90
[HTTP/2 200 OK 717ms]

GEThttps://jftest2.example.com/Items/8fb5747d826e9513fcee662a5aca8fbb/Images/Primary?tag=87ad5c1db3a90a3408eb0e64cb73afb8&quality=90
[HTTP/2 200 OK 717ms]

app is hidden apphost.js:205:21
```

**Screenshots**

image

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.5-dev

**Additional context**

Pretty sure this was working fine yesterday.

### PR DESCRIPTION
**Pull request by dmitrylyzo**
**Issues**
Fixes #852
Fixes #853

### CODE REVIEW

**Comment by PrplHaz4** [comment]
@dmitrylyzo this doesn't seem to fix the attached issues (unless i'm running into a cache problem) - the only change in this commit looks like fixing a debug line...

**Comment by dmitrylyzo** [comment]
@PrplHaz4 this little error prevents the execution of the following code.

**Comment by PrplHaz4** [comment]
Thanks @dmitrylyzo. I did build and restart before testing the change. Guess I'll have to improve my cache busting skills and verify the new code is being run.

**Comment by PrplHaz4** [comment]
> 
> 
> Thanks @dmitrylyzo. I did build and restart before testing the change. Guess I'll have to improve my cache busting skills and verify the new code is being run.

Confirmed cache was stale then deleted /dist, rebuilt, restarted server and all is good - both issues fixed - thanks for the quick response @dmitrylyzo and @joshuaboniface!

**Pull request merged**
