### PR TITLE
Fix dashboard column & update purple haze 

### PR DESCRIPTION
**Pull request by grafixeyehero**
Dashboard column **Before**

Screenshot_2019-05-03 Jellyfin(2)

Dashboard column **After** and some update on  **Purple haze color**

Screenshot_2019-05-03 Jellyfin

### CODE REVIEW

**Comment by dkanada** [comment]
What exactly is fixed on the dashboard page?

**Comment by grafixeyehero** [comment]
Look closely on the dashbord before on activity and  alerts cloumn

**Comment by joshuaboniface** [comment]
So it looks like we're just removing the Alerts column, correct? I'm Ok with this, though ideally it would be useful instead.

**Comment by grafixeyehero** [comment]
Not removing scrolldown it's there

**Comment by grafixeyehero** [comment]
@joshuaboniface 
Didn't remove alerts scrolldown u can find on the bottom

**Pull request merged**
