### PR TITLE
Use builtins when injecting core-js

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

This should slightly reduce the amount of core-js polyfills inserted into bundle.js, by only inserting what we actually need.

**Issues**

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
Now new Shaka doesn't break webOS 1.2, but I got error:
`nowPlayingPositionSlider.enableKeyboardDragging` is `undefined`
https://github.com/jellyfin/jellyfin-web/blob/0849ea77d8f17a9e4db9449b1cf62d9bb3e90604/src/controllers/playback/videoosd.js#L1353
Does `CustomElements` work differently now?

**Comment by dmitrylyzo** [comment]
I tried to move `babel/polyfill` to the very top on `master` and got the same error.
Looks like we need to load `webcomponents` before `core-js`.

**Comment by MrTimscampi** [comment]
> Looks like we need to load `webcomponents` before `core-js`.

Afaik, core-js's injection always goes at the top of the file. However, the polyfill for Web Components v0 (the one we use) is `document-register-element`. `webcomponents.js` is for the v1 API, which we want to migrate to at some point, probably.

**Comment by dmitrylyzo** [comment]
I have moved `shaka-player` in `bundle.js` after `babel/polyfill` in `master` branch - **webOS 1.2 is happy**.
Loading order:
```
document-register-element -> adds document.registerElement
webcomponents -> changes document.registerElement
babel/polyfill -> adds Symbol
shaka-player
```

**Some thoughts**
- We have several polyfills for one API.
- Not all polyfills are the same.
- Order in `bundle.js` matters because our code is written for a specific API/polyfill implementation.
- There is a chance that polyfills in our `bundle.js` may break external modules.

**Comment by dkanada** [comment]
@dmitrylyzo is the current state of this PR causing issues with any clients?

**Comment by MrTimscampi** [comment]
> @dmitrylyzo is the current state of this PR causing issues with any clients?

We're removing Shaka, so it should be good. But it'll need some rework once Shaka is removed, so better wait for the dead code removal first.

**Pull request closed without merging**
