### PR TITLE
Rename whitelist/blacklist

### PR DESCRIPTION
**Pull request by Influence365**
**Changes**
Whitelist/blacklist replaced with allow list/block list

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Actually, can we replace the "blacklist" label in all the translations too? Otherwise those will become orphaned and force retranslation.

**Comment by Influence365** [comment]
We could leave this for 10.6.x or 10.7.0 so the server-side info can be changed as well?

**Comment by Influence365** [comment]
> Actually, can we replace the "blacklist" label in all the translations too? Otherwise those will become orphaned and force retranslation.
Will do

**Comment by joshuaboniface** [comment]
I think for UI puposes, this + changes to the translations is good enough, then we could rename IsRemoteIPFilterBlacklist and such after 10.6.z for 10.7.0.

**Comment by joshuaboniface** [comment]
>Do i just add the strings to the other language files and leave the translation blank?

From a quick check, just a `sed 's/Whitelist/Allowlist/g' 's/Blacklist/Blocklist/g'` on the `src/strings/*.json` files would be sufficient.

**Comment by MrTimscampi** [comment]
Not to start a political debate or anything, but I think this is a bit reactionary and is generally done more for posturing like "look, we're inclusive" than really being for a deeper societal change.

I'm not against it in principle, because racism sucks and should've gone to die in a fire like 500 years ago, but to me, it takes more than getting rid of terms we don't like to change things.

I do think that, if we do this, it should be under a few conditions:

1. Go down the chain. Don't only change the surface terms, that's ridiculous.
2. Enact a Code of Conduct to go with this.
3. Build and discuss a list of the potentially offensive terms with all users of Jellyfin, emphasizing the need for feedback from different cultures and walks of life.

Imo, either we do this properly or we don't do it at all.

**Comment by joshuaboniface** [comment]
I think that's a reasonable stance @MrTimscampi and I agree that we shouldn't just jump on this bandwaggon because there's a bunch of news stories about project switching their terms this week. If we're going to do this, let's do this right, and that will involve a lot of code tweaks and consultation with our myriad of users, contributors, and translators (note - most of these translations are literal translations of "black list" and "white list", so for this to actually be anything other than posturing, we'd need to change them all).

**Comment by MrTimscampi** [comment]
Adding the relevant tags, to make sure it's not merged before being discussed further.

**Comment by sparky8251** [comment]
I mean, I vote no if it matters. [Blacklist](https://en.wikipedia.org/wiki/Blacklist_(computing)) and [whitelist](https://en.wikipedia.org/wiki/Whitelisting) have clearly defined meanings in computing. [The terms don't even have racist origins](https://en.wikipedia.org/wiki/Blacklisting#Origins_of_the_term) (and whitelisting literally only exists in computing as the opposite of blacklisting so...).

To me this is needless pandering and will only serve to muddy the waters on terms used for decades over problems that don't exist for no benefit to the people it supposedly harms (but will anger those less understanding causing them harm over literally nothing).

**Comment by Influence365** [comment]
I agree, I did not wish to cause any debates or any controversy by this pr. With software like Chrome/Android/GitHub going in the direction of removing the above references, I thought it would be a good step for Jellyfin to follow in a similar direction.

> 1. Go down the chain. Don't only change the surface terms, that's ridiculous.

As for going down the chain. These are the only references to blacklist/whitelist in Jellyfin-web. I can continue and change the values in the Jellyfin server side if we decide to do this.

> 2\. Enact a Code of Conduct to go with this.

There is a [Contributor Covenant Code of Conduct](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project) available as the default code of conduct that is produced by Github, this could be used as a starting point. 

> 3\. Build and discuss a list of the potentially offensive terms with all users of Jellyfin, emphasizing the need for feedback from different cultures and walks of life.

With regards to above, an issue could be created discussing potentially offensive terms and they could be changed/removed as necessary.

I will be more than happy to close this if it felt that the changes should not be made.

**Comment by joshuaboniface** [comment]
No worries @Influence365 I think it was inevitably going to be brought up given the very high profile discussions of this over the past week. I'm hesitant to open an issue because I'm certain it will have to be locked very quickly, which defeats the entire purpose of an issue about it, but it's definitely something to keep in mind.

Let's let this whole thing simmer for a bit, we can leave this PR open, and revisit this in a couple weeks once the dust settles. Given that I'm *just* about to announce the feature freeze for 10.6.0 it's not the best time to go through the whole codebase anyways.

For 1 we're referring to the actual variable that this sets, `IsRemoteIPFilterBlacklist`, which is a config option that gets saved and used in the backend, so this would touch the backend code as well.

**Comment by sparky8251** [comment]
For what its worth, I agree with @joshuaboniface @Influence365. With all this stupid term changing going on, *someone* was going to bring it up. Glad it was you rather than someone militantly PC :)

I'm sure we can figure something out given time, even if its just keeping it all as is.

**Comment by agilob** [comment]
>Actually, can we replace the "blacklist" label in all the translations too? Otherwise those will become orphaned and force retranslation.

Please also consider that "blacklist" and "whitelist" are easy to translate into other languages where translations of these words don't include colours "black" and "white" and none non-English native speaker ever thinks about linking them with some racial context. Changing wording in invisible for users variable names is one thing, but changing visible translations is another thing.

**Comment by joshuaboniface** [comment]
@agilob Indeed, for fun I spot-checked this and at least 5 of the random languages I checked were literal translations of "black list" or "white list", as diverse as French, Finnish, and Turkish. Clearly this is not just a simple replacement and goes deeper.

If the entire tech world wants to change this, that's fine, but I don't see much reason for us to be rushing to the forefront of it. I'd rather see how other well-internationalized projects handle it first and use their examples.

**Comment by tktbbjetaime** [comment]
Those cucks

**Comment by Nyazuma** [comment]
The most usefull commit ever. You guys are seriously trigger by anything.

**Comment by joshuaboniface** [comment]
Well, I think after 25 days this issue *has* simmered down, and... just about as expected, it was basically forgotten and no one is talking about it any more. I'm sure there's still thousands of software projects using this terminology. So as previously mentioned, let's close this PR for now since it's inadequate, and if someone wants to do the work by all means, but I think keeping these terms is fine. Exporting American sociopolitical arguments to our global community is not something worth encouraging.

**Pull request closed without merging**
