### PR TITLE
Remove unused image types

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Removes unused image types from the web client (ie images we don't surface anywhere):

* Menu
* Box
* Box (rear)
* Disc

**Issues**

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Note: there is also "Art", which has no reference in web and is unused, but I'm not sure what it is, so leaving it for now.

**Comment by Artiume** [comment]
I'm still on the fence about this cleanup. I dont have any disc images at the moment but I know those who collect them

**Comment by MrTimscampi** [comment]
> I'm still on the fence about this cleanup. I don't have any disc images at the moment but I know those who collect them

They're unused and none of our clients surface them, except maybe Kodi. Leaving them enabled is kind of misleading, imo, and Kodi can probably use its own artwork providers to fetch these if wanted.

**Comment by dkanada** [comment]
So what images are we actually keeping then?

**Comment by mcarlton00** [comment]
That I know of, Kodi only utilizes Poster, Backdrop, and Banner depending on the skin

**Comment by Artiume** [comment]
We might eventually get a metadata source that provides these images. Or there might be those that use it now in their own systems. They aren't hurting anyone and I think they should just stay until we have a reason to remove them

**Comment by dkanada** [comment]
I think I'll vote for leaving them in right now.

**Pull request closed without merging**
