### PR TITLE
Changed playback time info item to a known "human readable" format.

### PR DESCRIPTION
**Pull request by DerNormal**
**Changes**
Changed some code so the playback time won't be displayed as "134 mins" anymore.
Now it will be displayed e.g. as 02h14m. 1 minute will be 00h01m.

**Issues**
None

Please adopt the code <3

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Thanks for your contribution.

There are a few issues with this code, both in formatting (it's tripping our linter) and in design.

Here's the linting errors:

```
  388:1   error    Expected indentation of 8 spaces but found 6                                                                   indent
  389:1   error    Expected indentation of 12 spaces but found 8                                                                  indent
  390:1   error    Expected indentation of 12 spaces but found 8                                                                  indent
  390:36  error    Statement inside of curly braces should be on next line                                                        brace-style
  390:38  error    This line has 2 statements. Maximum allowed is 1                                                               max-statements-per-line
  390:55  error    Closing curly brace should be on the same line as opening curly brace or on the line after the previous block  brace-style
  391:1   error    Expected indentation of 12 spaces but found 8                                                                  indent
  392:1   error    Expected indentation of 8 spaces but found 6                                                                   indent
  394:1   error    Expected indentation of 8 spaces but found 6                                                                   indent
```

For the design part, I am personally not a fan of "00h01m". I also wouldn't bother with handling dates manually when there are really good and small libraries like [date-fns](https://www.npmjs.com/package/date-fns) available to format dates and durations for us and support localization.

**Comment by dkanada** [comment]
@MrTimscampi I definitely prefer showing hours to minutes, why do you dislike them?

**Comment by MrTimscampi** [comment]
@dkanada Movies are usually shown in minutes.

However, my issue is more with stuff like 00h01m. It doesn't make much sense to show leading zeroes here.

I'm more for a toggle at some point, but with a proper time library and format.

This also doesn't support localization, so languages with different formats (like Japanese) will have the wrong formatting.

**Comment by DerNormal** [comment]
Me for my part, I won't change anything more than that. If anyone thinks my changes are bad, feel free to implement whatever you'd like to see.

**Comment by MrTimscampi** [comment]
But a digital clock shows time, not duration.

To me, duration is 1h30min or 90min or 40min. Never 0h30min.

Plus,e do need some way to handle time in different languages.

Adding a library wouldn't mean we'd only use it here, we would deploy it through de web client.

**Comment by DerNormal** [comment]
This gets too complicated for such a small improvement.

**Comment by joshuaboniface** [comment]
I don't want to discourage from contributing, but the localizations are very important here, and trying to do a "human readable" format that works across multiple variant cultures would be a bit of a pain. With just a "minutes" value, it's quite easy to translate into almost every language, but even between European languages there's differences between the display of hour-minute time formats.

That, and a lot of places, including IMDB, show the "minutes-only" runtime first/only, so it's not unusual that we (and Emby) do too.

**Comment by Exypo** [comment]
Could this pull request be deleted by any chance? I don't want this to be online visible anymore.
I just accept how it is.

**Comment by AndreasGB** [comment]
This doesn't seem possible according to https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Comment by dkanada** [comment]
@Exypo I can confirm that we can't on our end, although I did go looking for a bit. If you don't want the commits to show up you can always force push your branch with your changed removed.

**Comment by Exypo** [comment]
Not possible anymore, sorry. Already deleted the forked repo.

**Pull request closed without merging**
