### PR TITLE
Library URL Path Corrected

### PR DESCRIPTION
**Pull request by Artiume**
URL was working properly using redirects. Corrected Path to new URL.

**Changes**

**Issues**

### CODE REVIEW

**Comment by oddstr13** [comment]
I believe the plan was to move documentation over to the subdomain eventually?
It just hasn't been done yet.

**Comment by JustAMan** [comment]
Ping @joshuaboniface or @anthonylavado for clarification

**Comment by anthonylavado** [comment]
So the plan is indeed to have a sub domain for docs, and this redirect is standing until we get that finished.

**Comment by Artiume** [comment]
So this PR should be canceled. With the redirect, the current link works and my fix is going in the wrong direction.

**Pull request closed without merging**
