### PR TITLE
Fix Progressive Stream 'P' capitalization

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

### CODE REVIEW

**Comment by Artiume** [comment]
Let me verify. I might need to rescan my media but currently the codec details is missing on the media page

**Comment by Artiume** [comment]
A fresh build with jf#3113 and this PR is still giving me a `TypeError: page.querySelector(...) is null`  error.
 I think I'm missing some logic. Im building just 3113 to see what happens

**Comment by dmitrylyzo** [comment]
> A fresh build with jf#3113 and this PR is still giving me a `TypeError: page.querySelector(...) is null` error.
> I think I'm missing some logic. Im building just 3113 to see what happens

I don't see any relation of this PR to the server.

**Comment by Artiume** [comment]
With the PR's, my codec details disappear and content isn't playable. I keep getting `uncaught exception: Object` in my console

image

**Comment by MrTimscampi** [comment]
> With the PR's, my codec details disappear and content isn't playable. I keep getting `uncaught exception: Object` in my console
> 
> image

Different issue, that's the regression I found yesterday, which is fixed in https://github.com/jellyfin/jellyfin/pull/3118

**Pull request merged**
