### PR TITLE
fix: legacy JASSUB wasm

### PR DESCRIPTION
**Pull request by ThaUnknown**
production mode makes Terser run on ALL files even statically copied ones, and since it has dead code removal it can remove dynamic code [bad!]
**Changes**

Used a custom TerserPlugin configuration, which copies [webpack's default](https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1339), and simply excludes `.wasm.js` files which terser was breaking. Regrettably I had to undo the import based URL loading for the `.wasm.js` file in question, and instead use static copy as I couldn't get it to work via imports, not sure why, this could be improved upon
**Issues**

Maybe #4794 ? Needs testing.

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
[`Math.clz32`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32) and [`Math.fround`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/fround) polyfills are required. Who knows what else. But it started working on webOS 1.2

That's probably because you have removed the chrome version option from the emscripten command when making the combined build.

**Comment by ThaUnknown** [comment]
iirc the min versions were removed because they forcefully enabled emscripten's closure compiler, which removed their own code and prevented the library from working at all

guess I'll spend a few more hours debugging their code once again, if not I'll have to polyfill all this stuff manually

**Comment by dmitrylyzo** [comment]
> the polyfills are missing but the library works fine? or was it after you simply added all of core.js?

I added them to `jassub-worker.wasm.js` in `dist`.
Btw, this also works for the current `master` (without this PR).

**Comment by ThaUnknown** [comment]
is that when you copy over the wasm.js or is it when u add said polyfills to the worker?

**Comment by ThaUnknown** [comment]
> [`Math.clz32`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32) and [`Math.fround`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/fround) polyfills are required. Who knows what else. But it started working on webOS 1.2
> 
> That's probably because you have removed the chrome version option from the emscripten command when making the combined build.

I've re-introduced min browser versions, the issues they caused were fixed in the version of emscripten i've updated to a while back

**Comment by dmitrylyzo** [comment]
> is that when you copy over the wasm.js or is it when u add said polyfills to the worker?

1. Checkout `jellyfin-web:master`.
2. Install modules.
3. Install (add) `jassub@1.7.12`.
4. Add 2 polyfills to `dist/jassub-worker.wasm.js` at the beginning.
5. Build jellyfin-web.

**Comment by ThaUnknown** [comment]
> > is that when you copy over the wasm.js or is it when u add said polyfills to the worker?
> 
> 1. Checkout `jellyfin-web:master`.
> 2. Install modules.
> 3. Install (add) `jassub@1.7.12`.
> 4. Add 2 polyfills to `dist/jassub-worker.wasm.js` at the beginning.
> 5. Build jellyfin-web.

this just flat out doesnt work

I get JF master, build it, copy it over to my JF installation, no playback works on any browser

**Comment by rafma0** [comment]
hmm, this is whats happening when I try to set 2 different ASS tracks on Tizen and then turn it off, using latest master or this PR. am I missing something @dmitrylyzo ?

image

**Pull request closed without merging**
