### PR TITLE
Add restart warning to upnp

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

https://github.com/jellyfin/jellyfin/issues/2401

### CODE REVIEW

**Comment by PrplHaz4** [comment]
Is it really only restart to disable or is it restart the server for changes to take effect.

**Comment by Artiume** [comment]
Not sure

**Comment by Artiume** [comment]
There's a lot of settings that require restart to take effect. Do we want the warning to list them all? And personally, I like the warning there instead of a pop up. If I know it requires a system restart, chances are I'm less likely to mess with the setting.

**Comment by PookaMustard** [comment]
@Artiume @PrplHaz4 I used the issue linked in the OP to find out which scenarios required a restart to trigger or stop the issue and which didn't. Here's what I found:

- **DLNA Play To** triggers #2401 without restart. Restarting required for stopping it.
- **Automatic port forwarding** requires a restart for triggering AND stopping #2401.

**Comment by dkanada** [comment]
It's not a dialog, it's just stored in a separate string file so we wouldn't need to list them all. All we need to do is append the generic `This option requires a restart to take effect.` for any applicable settings.

**Comment by Artiume** [comment]
Does that string already exist or would we need to add its implementation?

**Comment by dkanada** [comment]
I think it exists somewhere, but if it doesn't we should make it now.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/blob/7e369da67b7b0965258e0ba1d9310f4bd3182bf1/src/networking.html#L88 

What'd be the best way to add the new variable?

**Comment by dkanada** [comment]
added to #801

**Pull request closed without merging**
