### PR TITLE
Update server and quick connect icons

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Update icons to something maybe a bit more fitting?

Screenshot 2022-10-20 at 17-39-02 Jellyfin

**Issues**
N/A

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I prefer the current quick connect icon above this one. It kind of illustrates that quick connect is used to authenticate another device.

**Comment by thornbill** [comment]
Ok how about this one then?

Screenshot 2022-10-21 at 17-16-11 Material Design Icons DX

The current one makes me think I'll be casting to another device not something to deal with authentication. :man_shrugging:

**Comment by nielsvanvelzen** [comment]
I guess that one looks better yeah

**Comment by thornbill** [comment]
Screenshot 2022-10-24 at 14-02-16 Jellyfin

Updated the quick connect icon to use that one.

**Review by nielsvanvelzen — APPROVED** [review]

**Review by anthonylavado — APPROVED** [review]

**Comment by mueslimak3r** [comment]
Can the same quick connect icon that’s in the top left be used here?

**Pull request merged**
