### PR TITLE
Update page title for navigation and now playing

### LINKED ISSUE #1147: Update page title for navigaion and now playing music
When browsing Jellyfin web it seems to update the page title randomly. I can see it updates for entering a video library and playing a video. However it does not appear to update the title for any other pages or for now playing music. I would expect the title to always show the now playing music. When music or a video is not playing then every page should update the title instead of just defaulting to Jellyfin.

### PR DESCRIPTION
**Pull request by JasonGhent**
**Changes**
Update page title for navigation and now playing.

**Issues**
Fixes #1147

### CODE REVIEW

**Comment by dkanada** [comment]
Browsers will already show an indicator when audio is playing from a tab, and I think it's better to show the current page rather than the current song, since that is also handled by most browsers in a more native fashion.

**Comment by Nickbert7** [comment]
> Browsers will already show an indicator when audio is playing from a tab, and I think it's better to show the current page rather than the current song, since that is also handled by most browsers in a more native fashion.

At least for music I'd like to see the name of the current song playing in the background in another tab.
Just the indicator doesn't tell me enough.
As a compromise, you could only show that on the now playing page.

**Comment by MrTimscampi** [comment]
IMO, it should only be shown on the Now Playing page (and maybe the video playback page), as the other pages should keep their title while navigating the client.

I also think the code in this PR is needlessly minified, which makes it harder to read than it should be. The clarity of code is better than conciseness.

**Comment by dkanada** [comment]
We decided to avoid changing the tab name with the now playing information for two reasons. Icons generally don't look good in tab names, and we already have extremely good media session support, which will display that information in most cases.

**Pull request closed without merging**
