### PR TITLE
Enable mp4 transcoding when supported

### PR DESCRIPTION
**Pull request by eyezak**
**Changes**
Enable fmp4 in all supported cases
Fix safari15 quirks
Tested safari15, chrome, firefox

### CODE REVIEW

**Comment by thornbill** [comment]
We have an option to enable fmp4 support currently on a per-user basis. Do these changes take that into account? Or replace it entirely? I do not see any updates to the setting itself here. Thanks!

**Comment by dmitrylyzo** [comment]
> We have an option to enable fmp4 support currently on a per-user basis. Do these changes take that into account? Or replace it entirely? I do not see any updates to the setting itself here. Thanks!

https://github.com/jellyfin/jellyfin-web/blob/98e8bf3061bb15cc6472fab801518396bc3c6076/src/scripts/browserDeviceProfile.js#L700

There was another PR: https://github.com/jellyfin/jellyfin-web/pull/2520
It was almost good to me.

@eyezak I see no reason to change order then `push`/`unshift` - fMP4 is better if supported and enabled (prefered).
All we need is to find out in what amount it is supported (codecs).

**Comment by eyezak** [comment]
> 

sorry i didn't get back to this, you are correct I make 'prefer' a preference but with https://github.com/jellyfin/jellyfin/pull/7325 the server honours the order correctly. What is the desired behaviour for this flag?
i will take a look at #3442 with this server change

**Comment by nyanmisaka** [comment]
fmp4 seeking is still broken in hls.js that used on non-Safari browsers. That's the reason why I haven't make it as default.

**Comment by knackebrot** [comment]
https://github.com/jellyfin/jellyfin-web/issues/3416

**Pull request closed without merging**
