### PR TITLE
Check if it's actually possible to play the item before trying to play it from itemDetails

### PR DESCRIPTION
**Pull request by edvwib**
This will simply not play the item if the playbackManager says it can't.
The issue described the expected behaviour to be to show a bigger version of the image, however I did not find an easy way to do that right now 😅 

This should however be better than displaying the error dialog.

**Issues**
Fixes: #4234

### CODE REVIEW

**Comment by thornbill** [comment]
Would it be possible to have this checked before adding the click handler?

**Comment by edvwib** [comment]
Good point. It's possible, but if I understand it correctly we then have to wait for the reload function to finish.

I've updated the PR, the reload function now returns a promise, so that way we can then check if we can play the item, and only then add the eventlistener.

**Review by dmitrylyzo — COMMENTED** [review]
There is also a pointer cursor that goes from the card CSS.
https://github.com/jellyfin/jellyfin-web/blob/856e0938cc3b0123fd50cc0638ad78501cbb0762/src/components/cardbuilder/card.scss#L23
https://github.com/jellyfin/jellyfin-web/blob/856e0938cc3b0123fd50cc0638ad78501cbb0762/src/components/cardbuilder/card.scss#L210
It would be nice to make it `unset` or `default` if the item isn't supported.

**Comment by edvwib** [comment]
Yeah it would be nice to get rid of the cursor. Of course it's possible, but I haven't figured out a nice way to do it... 😕

**Comment by thornbill** [comment]
Yeah unfortunately a lot of things are pretty hacked together in the older code. Maybe you could just add a class to the element if it should show the pointer cursor?

**Comment by dmitrylyzo** [comment]
It looks like we can open a copy of the actor's details in a new tab using the poster - it is an "anchor" with the correct `href`.
And it is uncontrollable: https://github.com/jellyfin/jellyfin-web/blob/69053a131f1c01b6ce018795ade07fd6adeddb08/src/components/cardbuilder/cardBuilder.js#L1352

**Comment by edvwib** [comment]
That's the page we're already on though, isn't it? The link is valid, but has no effect since it's the same url.

**Comment by dmitrylyzo** [comment]
> That's the page we're already on though, isn't it? The link is valid, but has no effect since it's the same url.

There is no (visual) effect when you click the left mouse button, but clicking the middle mouse button opens a new tab (or open the context menu and click "Open in a new tab").

I don't think we need such feature on the poster. But if we leave it, we should leave the pointer cursor.

**Comment by thornbill** [comment]
I haven't tested it, but I had an idea for a potentially easier approach... could we change this to use a `<span>` when it can't be played? There is a `canPlay`check a few lines below that could be combined with this.

https://github.com/jellyfin/jellyfin-web/blob/master/src/components/cardbuilder/cardBuilder.js#L1459

**Comment by thornbill** [comment]
> I haven't tested it, but I had an idea for a potentially easier approach... could we change this to use a `<span>` when it can't be played? There is a `canPlay`check a few lines below that could be combined with this.
> 
> https://github.com/jellyfin/jellyfin-web/blob/master/src/components/cardbuilder/cardBuilder.js#L1459

I messed with this a bit but couldn't get it to work properly... so I guess the only thing remaining is dmitry's feedback above. :slightly_smiling_face:

**Comment by thornbill** [comment]
Superseded by #4881

**Pull request closed without merging**
