### PR TITLE
pull fonts from official repository

### PR DESCRIPTION
**Pull request by dkanada**

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
If this is merged we **must** update the documentation and add a note to the 10.7 release notes to warn people that enabled CSP to update their configuration.

All documentation for reverse proxies (like [nginx](https://jellyfin.org/docs/general/networking/nginx.html)) don't include the Jellyfin repository at this moment in the CSP config.

**Comment by MrTimscampi** [comment]
It's important to not that currently, the CSS files on our repository will load content from Google servers.

Do we want that or not?

**Comment by dkanada** [comment]
Someone mentioned it on Matrix, and I'll be fixing it soon.

**Review by MrTimscampi — APPROVED** [review]

**Review by ferferga — APPROVED** [review]
All good now!

**Pull request merged**
