### PR TITLE
ignore .DS_Store

### PR DESCRIPTION
**Pull request by felix920506**
ignores .DS_Store file created by macOS finder
https://en.wikipedia.org/wiki/.DS_Store

**Issues**
None

### CODE REVIEW

**Comment by thornbill** [comment]
You should probably configure this (and any other OS specific ignores) globally.

**Comment by felix920506** [comment]
I saw it in the main repo .gitignore so I figured it should probably be here as well
https://github.com/jellyfin/jellyfin/blob/master/.gitignore#L201-L202

**Comment by thornbill** [comment]
Personally I think it's better for people to deal with the specifics of their systems in the global config to avoid adding cruft to every repository they contribute to. 🤷‍♂️

**Comment by vreelb** [comment]
That's certainly the ideal, but for repositories that accept public contributions having the `.gitignore` cover something that a novice might accidentally commit saves reviewers the need to comment about it on their PRs.

**Pull request closed without merging**
