### PR TITLE
Add experimental UI

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Adds an "experimental" layout using [MUI](https://mui.com/) components

**TODO**
* [x] Some content is not using localized text
* [x] Custom link support in side menu
* [x] Plugin link support in admin side menu
* [x] Side menu state should be persisted on reload
* [x] Cast/remote play menu is incomplete
* [x] SyncPlay menu
* [x] Back button
* [x] Some pages layout are broken by the pinned sidebar
* [ ] Select server page should not show currently logged in user
* [x] Tabs are not displayed
* [x] Mobile menu should support clicking background to close
* [x] Mobile menu should support swiping to close
* [x] ~~Should [material-ui-popup-state](https://github.com/jcoreio/material-ui-popup-state) be used to simplify menu states?~~ I don't really see a need for it at this point.
* [ ] AppBar should hide on video OSD unless activated via mouse/keyboard
* [ ] AppBar should not wrap on small screens (iPhone SE)
* [x] ~~Investigate "new" built-in async support in react-router~~ This can be done independent of the UI work
* [ ] RTL support
* [ ] Theme support

**Related PRs**
* #4584 
* #4595
* #4616
* #4669
* #4705

**Issues**
N/A

### CODE REVIEW

**Comment by Im-Mefju** [comment]
On mobile screen, drawer is taking space even when closed. This bug isn't showing on legacy routes for some reason.

**Comment by thornbill** [comment]
@jellyfin-bot rebase

**Comment by thornbill** [comment]
@jellyfin-bot rebase

**Comment by thornbill** [comment]
Remaining issues are being tracked in https://github.com/jellyfin/jellyfin-web/issues/4815

**Pull request closed without merging**
