### PR TITLE
Add date episode added sorting

### LINKED ISSUE #3590: No 'Date Episode Added' sort option in TV Shows
**Describe The Bug**
It is not possible to sort TV shows by 'Last Episode Added' date, even though Jellyfin server supports it. This makes it practically impossible to find TV Shows with newly added seasons/episodes in a sizeable collection. As an example, I added a 2022-released season to a 2013-series, but I could not find it without scrolling down through 9 years of TV Shows. This is because Date Added uses the date the series was added, not the season or episode, and Release Date similarly uses the date the show first aired. Another product, Plex, has 'Last Episode Added' for this exact purpose.

**Steps To Reproduce**
1. Add a season to an old TV Show.
2. Use any of the existing sort options.
3. Notice the TV Show will never be at the top.

**Expected Behavior**
See description.

**System (please complete the following information):**
 - Platform: All
 - Browser: All
 - Jellyfin Version: 10.8.0-beta2

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Revival of https://github.com/jellyfin/jellyfin-web/pull/3591 with non-english translations removed and renamed option for "Date Show Added"

**Issues**
Fixes #3590

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by VickSyd** [comment]
where do i put these files ?

**Comment by VickSyd** [comment]
can someone tell me how to do the patch ? or will the angry man mark me as spam for the 3rd time ?  thought this was a helpful place

**Comment by VickSyd** [comment]
??

**Comment by VickSyd** [comment]
???

**Comment by VickSyd** [comment]
does a bot keep marking my post as spam ? or is it some angry incel

**Comment by VickSyd** [comment]
Angry Incel it is

**Pull request merged**
