### PR TITLE
remove "Customize Home Screen" Bar at Bottom of web ui

### PR DESCRIPTION
**Pull request by grafixeyehero**
#120

### CODE REVIEW

**Comment by dkanada** [comment]
I agree with @cvium, this button is too large and very useless in my opinion. I also don't think hiding the item when a user clicks it for the first time is a good solution either, which was mentioned in chat. Onboarding features like that are never very useful and create an ever-changing interface as they are hidden and shown to users.

**Comment by sparky8251** [comment]
Yup. I also 100% back removing it entirely.

No need for 3 links to the same place and it's always been an odd UI element since its only there on the "true" home screen and not similar looking screens.

**Comment by sparky8251** [comment]
That said, this removal appears incomplete.

The strings are still present in the strings files at the very least. There is also the possibility of some logic being stashed in a JS file.

Should first make sure removal is complete before accepting this PR.

**Comment by cvium** [comment]
The change is _in_ in the js file. The removal is complete afaict. Strings removal should be done from weblate?

**Comment by JustAMan** [comment]
> Strings removal should be done from weblate?

This is a tricky question, but I doubt weblate can remove items. So I would say remove them in this PR...

**Comment by grafixeyehero** [comment]
@cvium suggested it's done

**Comment by sparky8251** [comment]
The strings files are in `src/strings`.

You'll want to remove the lines containing `HeaderCustomizeHomeScreen` from any file in that folder to remove the string cruft.

**Comment by grafixeyehero** [comment]
@sparky8251 it's done

**Comment by sparky8251** [comment]
Just cause I've seen a lot of stupid with strings I checked for potential string variants that might have been from the olden days and never removed by Emby.

See no such thing! To me, it looks like this is ready for merging with no left over dead code.

**Comment by grafixeyehero** [comment]
i agree

**Pull request merged**
