### PR TITLE
Fix emby-scroller padded for mobile

### PR DESCRIPTION
**Pull request by grafixeyehero**
Before 
Screenshot

After
Screenshot (3)

### CODE REVIEW

**Comment by dkanada** [comment]
1. The scroll buttons shouldn't be visible on the mobile layout, so that's an issue.
2. I was concerned about the left margin, which should match the section header margin.

**Comment by grafixeyehero** [comment]
> The scroll buttons shouldn't be visible on the mobile layout, so that's an issue.

a simple fix like this 
@media all and (max-width:50em) {
    .emby-scrollbuttons {
        display: none !important
    }
}

**Comment by dkanada** [comment]
I thought I had only enabled them for the mobile layout though, which would be preferable to a css change.

**Comment by grafixeyehero** [comment]
> 
> 
> I thought I had only enabled them for the mobile layout though, which would be preferable to a css change.

closing the PR

**Pull request closed without merging**
