### PR TITLE
Audio boost when downmixing should be 0 - 3

### PR DESCRIPTION
**Pull request by ltomes**
This number input should have a range down to `0`

**Changes**
Changed minimum excepted value for downmixing to `0` from `0.5`
Please let me know if this requires changes, this is my first MR here/I just wanted to resolve this issue quick if it doesn't go too deep.

**Issues**

https://github.com/jellyfin/jellyfin-web/issues/4265

### CODE REVIEW

**Comment by thornbill** [comment]
> In retrospect I can see how removing sound at the transcoding level would generally be confusing, and might not be desirable for all of jellyfin's users. I understand if you just want to close this as not an issue.

So setting this value to 0 would effectively remove the sound when downmixing? I'm curious now what your use case for this is. :slightly_smiling_face:

**Comment by ltomes** [comment]
> > In retrospect I can see how removing sound at the transcoding level would generally be confusing, and might not be desirable for all of jellyfin's users. I understand if you just want to close this as not an issue.
> 
> So setting this value to 0 would effectively remove the sound when downmixing? I'm curious now what your use case for this is. 🙂

I don't have a great one, a library of pet videos with poor sound quality that I thought I would  boost the audio out of/didn't want to change the source of, and didn't want to make copies of.

**Comment by thornbill** [comment]
The team discussed this change a bit and the general consensus was we didn't want to enable this option. It mostly seems like it would just create issues when people change it without understanding the impact that it will have.

**Comment by ltomes** [comment]
I agree, I wanted this for a weird local library. but don't see the value for others (obviously I didn't realize that until after submitting the MR though).

**Pull request closed without merging**
