### PR TITLE
remove unused translation strings

### LINKED ISSUE #1247: Check for usage of translations without a source string
The following translation exist without a source en_US translation.

This issue is to track usage checking an removal.

- [ ] Accept
- [ ] AddGuideProviderHelp
- [ ] AddUser
- [ ] AddUserByManually
- [ ] AllowDeletionFromAll
- [ ] AllowSeasonalThemes
- [ ] AllowSeasonalThemesHelp
- [ ] AnamorphicVideoNotSupported
- [ ] AndroidUnlockRestoreHelp
- [ ] AudioBitDepthNotSupported
- [ ] AudioBitrateNotSupported
- [ ] AudioChannelsNotSupported
- [ ] AudioCodecNotSupported
- [ ] AudioProfileNotSupported
- [ ] AudioSampleRateNotSupported
- [ ] AutomaticallyConvertNewContent
- [ ] AutomaticallyConvertNewContentHelp
- [ ] AutomaticallySyncNewContent
- [ ] AutomaticallySyncNewContentHelp
- [ ] BestFit
- [ ] BobAndWeaveWithHelp
- [ ] ButtonAccept
- [ ] ButtonCancelSeries
- [ ] ButtonChangeContentType
- [ ] ButtonClear
- [ ] ButtonClose
- [ ] ButtonConfigurePassword
- [ ] ButtonConfigurePinCode
- [ ] ButtonConvertMedia
- [ ] ButtonCreate
- [ ] ButtonExit
- [ ] ButtonHide
- [ ] ButtonInviteUser
- [ ] ButtonManageFolders
- [ ] ButtonManageServer
- [ ] ButtonMenu
- [ ] ButtonMoreInformation
- [ ] ButtonMute
- [ ] ButtonNewServer
- [ ] ButtonNext
- [ ] ButtonNo
- [ ] ButtonNowPlaying
- [ ] ButtonPlaylist
- [ ] ButtonPlayOneMinute
- [ ] ButtonPlayTrailer
- [ ] ButtonPreferences
- [ ] ButtonPrevious
- [ ] ButtonPrivacyPolicy
- [ ] ButtonProfileHelp
- [ ] ButtonPurchase
- [ ] ButtonQuality
- [ ] ButtonRecord
- [ ] ButtonReenable
- [ ] ButtonReject
- [ ] ButtonRemote
- [ ] ButtonRemoteControl
- [ ] ButtonReports
- [ ] ButtonReset
- [ ] ButtonResetTuner
- [ ] ButtonRestartNow
- [ ] ButtonRestorePreviousPurchase
- [ ] ButtonScanLibrary
- [ ] ButtonScheduledTasks
- [ ] ButtonSelect
- [ ] ButtonSendInvitation
- [ ] ButtonServer
- [ ] ButtonServerDashboard
- [ ] ButtonShare
- [ ] ButtonSignUp
- [ ] ButtonSkip
- [ ] ButtonStopRecording
- [ ] ButtonSync
- [ ] ButtonTryAgain
- [ ] ButtonUnlockPrice
- [ ] ButtonUnlockWithPurchase
- [ ] ButtonUnmute
- [ ] ButtonUpdateNow
- [ ] ButtonView
- [ ] ButtonViewAlbum
- [ ] ButtonViewArtist
- [ ] ButtonYes
- [ ] CancelDownload
- [ ] CategoryApplication
- [ ] CategoryPlugin
- [ ] CategorySync
- [ ] CategorySystem
- [ ] CategoryUser
- [ ] CinemaModeConfigurationHelp2
- [ ] CinemaModeFeatureDescription
- [ ] CloudSyncFeatureDescription
- [ ] ConfirmRemoveDownload
- [ ] ContainerBitrateExceedsLimit
- [ ] ContainerNotSupported
- [ ] Continue
- [ ] ContinueInSecondsValue
- [ ] Convert
- [ ] ConvertingDots
- [ ] ConvertItemLimitHelp
- [ ] ConvertUnwatchedVideosOnly
- [ ] ConvertUnwatchedVideosOnlyHelp
- [ ] Countries
- [ ] CoverArt
- [ ] Days
- [ ] DefaultCameraUploadPathHelp
- [ ] DeviceLastUsedByUserName
- [ ] DirectPlayError
- [ ] Downloaded
- [ ] Downloading
- [ ] DownloadingDots
- [ ] DownloadItemLimitHelp
- [ ] Downloads
- [ ] DvrFeatureDescription
- [ ] DvrSubscriptionRequired
- [ ] EnableDebugLoggingHelp
- [ ] EnterFFmpegLocation
- [ ] Error
- [ ] ErrorAddingGuestAccount1
- [ ] ErrorAddingGuestAccount2
- [ ] ErrorAddingJellyfinConnectAccount1
- [ ] ErrorAddingJellyfinConnectAccount2
- [ ] ErrorAddingJellyfinConnectAccount3
- [ ] ErrorConnectServerUnreachable
- [ ] ErrorMessagePasswordNotMatchConfirm
- [ ] ErrorMessageUsernameInUse
- [ ] ErrorReachingJellyfinConnect
- [ ] ErrorRemovingJellyfinConnectAccount
- [ ] Fill
- [ ] FolderTypeInherit
- [ ] FolderTypeMixed
- [ ] ForAdditionalLiveTvOptions
- [ ] FreeAppsFeatureDescription
- [ ] GuestUserNotFound
- [ ] HeaderAddDevice
- [ ] HeaderAddLocalUser
- [ ] HeaderAddTag
- [ ] HeaderAdvanced
- [ ] HeaderAirDays
- [ ] HeaderAudio
- [ ] HeaderAudioLanguages
- [ ] HeaderAudioTracks
- [ ] HeaderBackdrops
- [ ] HeaderBrandingHelp
- [ ] HeaderCameraUpload
- [ ] HeaderCameraUploadHelp
- [ ] HeaderCancelSyncJob
- [ ] HeaderChangeFolderType
- [ ] HeaderChangeFolderTypeHelp
- [ ] HeaderChapters
- [ ] HeaderCinemaMode
- [ ] HeaderClients
- [ ] HeaderCloudSync
- [ ] HeaderCollections
- [ ] HeaderColumns
- [ ] HeaderConfirm
- [ ] HeaderConfirmation
- [ ] HeaderConfirmDeletion
- [ ] HeaderConfirmRecordingCancellation
- [ ] HeaderConfirmRecordingDeletion
- [ ] HeaderConfirmRemoveUser
- [ ] HeaderConfirmSeriesCancellation
- [ ] HeaderConvertYourRecordings
- [ ] HeaderCreatePassword
- [ ] HeaderCredits
- [ ] HeaderDashboardUserPassword
- [ ] HeaderDate
- [ ] HeaderDeleteImage
- [ ] HeaderDestination
- [ ] HeaderDetails
- [ ] HeaderDevice
- [ ] HeaderDownloadSettings
- [ ] HeaderDownloadSubtitlesFor
- [ ] HeaderEmbeddedImage
- [ ] HeaderExport
- [ ] HeaderExternalPlayerPlayback
- [ ] HeaderExternalServices
- [ ] HeaderFavoriteCollections
- [ ] HeaderForgotKey
- [ ] HeaderFreeApps
- [ ] HeaderGuests
- [ ] HeaderHomePage
- [ ] HeaderHomeScreen
- [ ] HeaderHomeScreenSettings
- [ ] HeaderImageBackdrop
- [ ] HeaderImageLogo
- [ ] HeaderImagePrimary
- [ ] HeaderImages
- [ ] HeaderInvitations
- [ ] HeaderInvitationSent
- [ ] HeaderInviteUser
- [ ] HeaderInviteUserHelp
- [ ] HeaderInviteWithJellyfinConnect
- [ ] HeaderJellyfinAccountAdded
- [ ] HeaderJellyfinAccountRemoved
- [ ] HeaderJellyfinServer
- [ ] HeaderLanguage
- [ ] HeaderLatestChannelItems
- [ ] HeaderLatestChannelMedia
- [ ] HeaderLatestDownloadedVideos
- [ ] HeaderLatestFrom
- [ ] HeaderLatestFromChannel
- [ ] HeaderLatestItems
- [ ] HeaderLatestSongs
- [ ] HeaderLatestTrailers
- [ ] HeaderLatestTvRecordings
- [ ] HeaderLearnMore
- [ ] HeaderLibrary
- [ ] HeaderLinks
- [ ] HeaderManagement
- [ ] HeaderMediaLocations
- [ ] HeaderMenu
- [ ] HeaderMissing
- [ ] HeaderMyViews
- [ ] HeaderName
- [ ] HeaderNetwork
- [ ] HeaderNewApiKeyHelp
- [ ] HeaderNewRecording
- [ ] HeaderNewServer
- [ ] HeaderNewUsers
- [ ] HeaderNotifications
- [ ] HeaderNowPlaying
- [ ] HeaderNumberOfPlayers
- [ ] HeaderOffline
- [ ] HeaderOfflineDownloads
- [ ] HeaderOfflineDownloadsDescription
- [ ] HeaderOfflineSync
- [ ] HeaderOptions
- [ ] HeaderOtherDisplaySettings
- [ ] HeaderOverview
- [ ] HeaderParentalRating
- [ ] HeaderPersonInfo
- [ ] HeaderPhotoInfo
- [ ] HeaderPlaylists
- [ ] HeaderPlayMyMedia
- [ ] HeaderProgram
- [ ] HeaderRecentActivity
- [ ] HeaderRecordingGroups
- [ ] HeaderReleaseDate
- [ ] HeaderRequireManualLogin
- [ ] HeaderRequireManualLoginHelp
- [ ] HeaderResetTuner
- [ ] HeaderResolution
- [ ] HeaderRestartingJellyfinServer
- [ ] HeaderResult
- [ ] HeaderResume
- [ ] HeaderResumeSettings
- [ ] HeaderReviews
- [ ] HeaderScreenSavers
- [ ] HeaderSeason
- [ ] HeaderSeasonNumber
- [ ] HeaderSelectAudio
- [ ] HeaderSelectDevices
- [ ] HeaderSelectExternalPlayer
- [ ] HeaderSelectMediaPath
- [ ] HeaderSelectSubtitles
- [ ] HeaderSelectUploadPath
- [ ] HeaderSeriesRecordings
- [ ] HeaderServices
- [ ] HeaderShareMediaFolders
- [ ] HeaderSource
- [ ] HeaderSpecials
- [ ] HeaderSplitMedia
- [ ] HeaderSubtitles
- [ ] HeaderSupportTheTeam
- [ ] HeaderSync
- [ ] HeaderTime
- [ ] HeaderToAccessPleaseEnterEasyPinCode
- [ ] HeaderTopPlugins
- [ ] HeaderTrack
- [ ] HeaderTrailers
- [ ] HeaderTryPlayback
- [ ] HeaderTV
- [ ] HeaderType
- [ ] HeaderUpcomingEpisodes
- [ ] HeaderUpcomingNews
- [ ] HeaderVideo
- [ ] HeaderWaitingForWifi
- [ ] HeaderYear
- [ ] HowWouldYouLikeToAddUser
- [ ] ImdbRating
- [ ] InterlacedVideoNotSupported
- [ ] Invitations
- [ ] InviteAnJellyfinConnectUser
- [ ] KeepDownload
- [ ] LabelAddConnectSupporterHelp
- [ ] LabelAddedOnDate
- [ ] LabelAirDate
- [ ] LabelAnytime
- [ ] LabelArtist
- [ ] LabelBitrateMbps
- [ ] LabelCameraUploadPath
- [ ] LabelCameraUploadPathHelp
- [ ] LabelConfigureSettings
- [ ] LabelConvertTo
- [ ] LabelCustomizeOptionsPerMediaType
- [ ] LabelDefaultForcedStream
- [ ] LabelDefaultStream
- [ ] LabelDeinterlacingMethod
- [ ] LabelDisplayCollectionsView
- [ ] LabelDisplayCollectionsViewHelp
- [ ] LabelDisplayMissingEpisodesWithinSeasonsHelp
- [ ] LabelDownloadInternetMetadata
- [ ] LabelDownloadInternetMetadataHelp
- [ ] LabelEmail
- [ ] LabelEpisode
- [ ] LabelExternalPlayers
- [ ] LabelffmpegVersion
- [ ] LabelFolderType
- [ ] LabelFree
- [ ] LabelFriendlyServerName
- [ ] LabelFriendlyServerNameHelp
- [ ] LabelFromHelp
- [ ] LabelIpAddressValue
- [ ] LabelLastResult
- [ ] LabelLimit
- [ ] LabelLimitIntrosToUnwatchedConLoginDisclaimertent
- [ ] LabelMaxBitrate
- [ ] LabelRunningTimeValue
- [ ] LabelSeries
- [ ] LabelSubtitleLanguagePreference
- [ ] LabelSyncJobName
- [ ] LabelSyncNoTargetsHelp
- [ ] LabelSyncPath
- [ ] LabelSyncTempPath
- [ ] LabelSyncTempPathHelp
- [ ] LabelSyncTo
- [ ] LabelTranscodingTemporaryFiles
- [ ] LabelTranscodingTempPath
- [ ] LabelUnairedMissingEpisodesWithinSeasons
- [ ] LabelUnknownLanguage
- [ ] LabelUploadSpeedLimit
- [ ] LabelUrl
- [ ] LabelVersionNumber
- [ ] LabelWindowBackgroundColor
- [ ] LetterButtonAbbreviation
- [ ] LinkApi
- [ ] LinkCommunity
- [ ] LinkGithub
- [ ] LiveTvFeatureDescription
- [ ] LiveTvRequiresUnlock
- [ ] LiveTvUpdateAvailable
- [ ] LoginDisclaimer
- [ ] MarkWatched
- [ ] MediaInfoFormat
- [ ] Medium
- [ ] MessageApplicationUpdated
- [ ] MessageLoggedOutParentalControl
- [ ] MessageNamedServerConfigurationUpdatedWithValue
- [ ] MessageNoDownloadsFound
- [ ] MessageNoSyncJobsFound
- [ ] MessagePleaseRestart
- [ ] MessagePleaseRestartServerToFinishUpdating
- [ ] MessageServerConfigurationUpdated
- [ ] MissingBackdropImage
- [ ] MissingEpisode
- [ ] MissingLogoImage
- [ ] MissingPrimaryImage
- [ ] More
- [ ] NoPluginsInstalledMessage
- [ ] Open
- [ ] Option2Player
- [ ] Option3Player
- [ ] Option4Player
- [ ] OptionActor
- [ ] OptionActors
- [ ] OptionAnyNumberOfPlayers
- [ ] OptionArt
- [ ] OptionBeta
- [ ] OptionConvertRecordingsToStreamingFormatHelp
- [ ] OptionDev
- [ ] OptionDirector
- [ ] OptionEnableAutomaticServerUpdates
- [ ] OptionIso
- [ ] OptionLogo
- [ ] OptionMenu
- [ ] OptionMobileApps
- [ ] OptionOff
- [ ] OptionOn
- [ ] OptionRelease
- [ ] OptionTags
- [ ] OptionVideoBitrate
- [ ] Password
- [ ] PersonTypePerson
- [ ] PlaybackErrorNotAllowed
- [ ] PlaybackErrorPlaceHolder
- [ ] PlaybackSettings
- [ ] PlaybackSettingsIntro
- [ ] PlayOnAnotherDevice
- [ ] PleaseSelectDeviceToSyncTo
- [ ] PluginInstalledWithName
- [ ] PluginTabAppClassic
- [ ] PluginUninstalledWithName
- [ ] PluginUpdatedWithName
- [ ] PrivacyPolicy
- [ ] ProviderValue
- [ ] RefFramesNotSupported
- [ ] SecondaryAudioNotSupported
- [ ] SelectCameraUploadServers
- [ ] Standard
- [ ] StatsForNerds
- [ ] Subscriptions
- [ ] SubtitleCodecNotSupported
- [ ] SubtitleSettings
- [ ] SubtitleSettingsIntro
- [ ] SyncingDots
- [ ] SyncUnwatchedVideosOnly
- [ ] SyncUnwatchedVideosOnlyHelp
- [ ] TabDLNA
- [ ] TabImage
- [ ] TabLibrary
- [ ] TabLibraryAccess
- [ ] TabNavigation
- [ ] TabSync
- [ ] TabTV
- [ ] TitleLiveTV
- [ ] TitleServer
- [ ] TitleSupport
- [ ] TitleSync
- [ ] Trailer
- [ ] TryMultiSelect
- [ ] TryMultiSelectMessage
- [ ] Users
- [ ] ValueLinks
- [ ] ValueOneTrailer
- [ ] ValueSeriesYearToPresent
- [ ] ValueStatus
- [ ] ValueStudio
- [ ] ValueStudios
- [ ] VersionNumber
- [ ] VideoBitDepthNotSupported
- [ ] VideoCodecNotSupported
- [ ] VideoFramerateNotSupported
- [ ] VideoLevelNotSupported
- [ ] VideoProfileNotSupported
- [ ] VideoResolutionNotSupported
- [ ] ViewTypeTvShows
- [ ] WifiRequiredToDownload

### PR DESCRIPTION
**Pull request by telans**
Fix-up/rebase of #1264, plus every other unused string
Removes all strings not used with "${xyz}" or "translate.('xyz')"

**Issues**
Closes #1247 
Closes #1264

### CODE REVIEW

**Comment by telans** [comment]
This last commit will really need to be checked over, but I don't believe I took out anything needed.

**Comment by telans** [comment]
Reverted the second commit as I messed up the checks to see if they were being used

**Comment by dkanada** [comment]
```
- MediaInfoStreamTypeSubtitle
- MediaInfoStreamTypeEmbeddedImage
- MediaInfoStreamTypeData
```

This is why we have to be careful, at least two of those are used in the client through dynamically generating the translation keys.

**Comment by telans** [comment]
Yeah, I noticed I pulled through a few I shouldn't have

**Comment by telans** [comment]
Here's a list for what I can tell have no references to anything else:

https://pastebin.com/raw/jvGuLMCx

I've force pushed the branch to match removal of the above

**Comment by dkanada** [comment]
@telans if you want to update this one we can merge it now that the feature freeze is over. I'd like to remove the strings as soon as possible to fix any possible issues before the next release.

**Comment by dkanada** [comment]
I ran the script again in #1711 so I'll close this one.

**Pull request closed without merging**
