### PR TITLE
Add better "Date *" base strings

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by dkanada** [comment]
Where are these used in the web client?

**Comment by ThatNerdyPikachu** [comment]
See #459.

**Comment by thornbill** [comment]
It looks like these are also used for sorting options (See https://github.com/jellyfin/jellyfin-web/blob/82f171e99a705b6deb46805ff2332363cfe23f7b/src/components/tabbedview/itemstab.js#L442). We should either add new translation strings or append the colon in the item details view to avoid impacting the other places these translations are used.

**Comment by joshuaboniface** [comment]
I agree with @thornbill here, the colons belong in the actual string read, rather than in the message text. This just complicates translations.

**Comment by dkanada** [comment]
@ThatNerdyPikachu did you want to revert these strings and add new ones?

**Pull request closed without merging**
