### PR TITLE
Fix detail page positioning

### PR DESCRIPTION
**Pull request by dannymichel**
Fix this gap

Screen Shot 2020-02-05 at 3 54 06 AM

### CODE REVIEW

**Comment by MrTimscampi** [comment]
@dannymichel This is already covered as part of #762, sorry.

**Comment by dannymichel** [comment]
He’s got the wrong %

**Comment by dkanada** [comment]
Heh @MrTimscampi sounds like you might have got the wrong percent. I feel like it has to do with using percent as a value here though.

**Comment by dannymichel** [comment]
Yeah should be pixels but you guys do your thing. I was just fixing it

**Comment by dannymichel** [comment]
done https://github.com/jellyfin/jellyfin-web/pull/769

**Comment by jma-odoo** [comment]
I'll double check it, but yeah, I think the issue is with it being percent. I simply adjusted the value to fix it on my end (As can be seen in the screenshots on my PR, it's fixed there)

Pixels isn't a solution though (We're generally trying to get rid of pixels as a unit in the source).

As an aside, in this sort of cases where a fix is already awaiting review and/or merging, it's better if you use the review feature of Github to suggest a change on the existing PR.  
It makes it easier for us to keep track of what's awaiting to be merged (since sometimes the merge order matters) and it's generally better form to suggest changes.

**Comment by dannymichel** [comment]
@jma-odoo someone change it to ``3.8em`` then cause if you're doing em thats what it's gonna be

**Pull request closed without merging**
