### PR TITLE
Made details poster clickable for playing.

### PR DESCRIPTION
**Pull request by Supergamer1337**
Co-authored-by: Esaias Tilly <esaias@tillys.se>
**Changes**
Enables the detail poster to act as a play button.

**Issues**
#940

### CODE REVIEW

**Comment by MrTimscampi** [comment]
You should simply be able to add `action: 'play'` to the options passed to build the card.

**Comment by Supergamer1337** [comment]
When we tried to add `action: 'play'` clicking the card or play button on the card, does nothing.

**Comment by MrTimscampi** [comment]
Here's the proper way to do it in order for code to stay consistent:

```diff

diff --git a/src/controllers/itemDetails/index.js b/src/controllers/itemDetails/index.js
index 992eaf048..3404e5f2d 100644
--- a/src/controllers/itemDetails/index.js
+++ b/src/controllers/itemDetails/index.js
@@ -1,4 +1,4 @@
-define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSettings', 'cardBuilder', 'datetime', 'mediaInfo', 'backdrop', 'listView', 'itemContextMenu', 'itemHelper', 'dom', 'indicators', 'imageLoader', 'libraryMenu', 'globalize', 'browser', 'events', 'playbackManager', 'scrollStyles', 'emby-itemscontainer', 'emby-checkbox', 'emby-button', 'emby-playstatebutton', 'emby-ratingbutton', 'emby-scroller', 'emby-select'], function (loading, appRouter, layoutManager, connectionManager, userSettings, cardBuilder, datetime, mediaInfo, backdrop, listView, itemContextMenu, itemHelper, dom, indicators, imageLoader, libraryMenu, globalize, browser, events, playbackManager) {
+define(['loading', 'itemShortcuts', 'appRouter', 'layoutManager', 'connectionManager', 'userSettings', 'cardBuilder', 'datetime', 'mediaInfo', 'backdrop', 'listView', 'itemContextMenu', 'itemHelper', 'dom', 'indicators', 'imageLoader', 'libraryMenu', 'globalize', 'browser', 'events', 'playbackManager', 'scrollStyles', 'emby-itemscontainer', 'emby-checkbox', 'emby-button', 'emby-playstatebutton', 'emby-ratingbutton', 'emby-scroller', 'emby-select'], function (loading, itemShortcuts, appRouter, layoutManager, connectionManager, userSettings, cardBuilder, datetime, mediaInfo, backdrop, listView, itemContextMenu, itemHelper, dom, indicators, imageLoader, libraryMenu, globalize, browser, events, playbackManager) {
     'use strict';
 
     function getPromise(apiClient, params) {
@@ -729,8 +729,8 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
             overlayText: false,
             transition: false,
             disableIndicators: true,
-            disableHoverMenu: true,
             overlayPlayButton: true,
+            action: 'play',
             width: dom.getWindowSize().innerWidth * 0.5
         });
 
@@ -1865,6 +1865,10 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
             playCurrentItem(this, this.getAttribute('data-mode'));
         }
 
+        function onPosterClick(e) {
+            itemShortcuts.onClick.call(view.querySelector('.detailImageContainer .card'), e);
+        }
+
         function onInstantMixClick() {
             playbackManager.instantMix(currentItem);
         }
@@ -1951,6 +1955,7 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
         bindAll(view, '.btnCancelSeriesTimer', 'click', onCancelSeriesTimerClick);
         bindAll(view, '.btnCancelTimer', 'click', onCancelTimerClick);
         bindAll(view, '.btnDownload', 'click', onDownloadClick);
+        view.querySelector('.detailImageContainer').addEventListener('click', onPosterClick);
         view.querySelector('.trackSelections').addEventListener('submit', onTrackSelectionsSubmit);
         view.querySelector('.btnSplitVersions').addEventListener('click', function () {
             splitVersions(self, view, apiClient, params);
-- 
```

**Comment by EsaiasTilly** [comment]
We accidentally merged the branch to our master while trying to update to the latest version of index.js, so the new PR is https://github.com/jellyfin/jellyfin-web/pull/1737.

**Pull request closed without merging**
