### PR TITLE
Add branding settings page

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
* Moves branding settings to a separate dashboard page
* Fixes some styling issues with the `emby-textarea` component

Screenshot 2024-11-20 at 18-10-42 Jellyfin

**Issues**
N/A

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
We do have an endpoint to upload a custom splash screen to, perhaps we can add support for that in this new branding page?

**Comment by thornbill** [comment]
Yeah I was thinking about adding that in a separate PR to keep this one smaller. 😉

**Review by nielsvanvelzen — APPROVED** [review]
Everything seems to work as expected. Some feedback for future improvements:

- Allow uploading the splash image(mentioned in earlier comment)
- Displaying the current splash image
- Maybe rename "splash screen" to "server background image" or something similar to make it a bit more descriptive
- Previewing the login disclaimer for when markdown/html is used
  - Use a WYSIWYG editor, may be a bit overkill though
- Use a larger minimum height for both text areas so it's obvious they're not a single line input

**Comment by thornbill** [comment]
> Might be worth adding this feedback here [jellyfin/jellyfin-meta#81](https://github.com/jellyfin/jellyfin-meta/discussions/81) also

These items are either already supported or do not require support by the server. I did create #6335 to track them here though.

**Pull request merged**
