### PR TITLE
Add missing options for people metadata editor

### PR DESCRIPTION
**Pull request by scampower3**
**Changes**
Add missing options for people metadata editor mainly for music. Album Artist and Artist.

**Issues**

### CODE REVIEW

**Review by thornbill — COMMENTED** [review]
We should probably iterate over all `PersonKind` values to make this list (probably excluding "Unknown").

https://github.com/jellyfin/jellyfin-sdk-typescript/blob/openapi-unstable/src/generated-client/models/person-kind.ts#L22

**Comment by scampower3** [comment]
Would it be better if the it generates the options dynamically according to the personkind instead of hardcoding the options into the template file?

**Comment by thornbill** [comment]
I just noticed this change is included in https://github.com/jellyfin/jellyfin-web/pull/4858 also

**Review by thornbill — APPROVED** [review]
`AlbumArtist` was not included in the other PR. In the future, we should look at iterating over the enum of possible types from the SDK, but this is fine for a quick fix.

**Pull request merged**
