### PR TITLE
Add unit tests

### LINKED ISSUE #4872: Add tests to the project
Hi !

I see that the project is not covered by tests, am I missing something ?  
I think it would be very important to cover the project with tests.  
I know it's a big job, but we need it to stop regressions, improve stability and maintainability.  
Tests also help to understand the code (to get more contributors &mdash; like me).  
Do you need more arguments ?  

I volunteer to do it.  

I suggest one PR per covered file.  
I will be easy for people to help, by commenting on this post wich file they take.

### PR DESCRIPTION
**Pull request by Airthee**
**Changes**
Add unit tests to some `utils` files.

**Issues**

Fixes #4872

### CODE REVIEW

**Comment by thornbill** [comment]
@Airthee I'm trying to clean up some stale PRs... do you plan to continue working on this?

**Comment by Airthee** [comment]
Hi ! Sorry I didn't work on it since many months, but I will try to fix lint and remove draft when all is green.

**Comment by Airthee** [comment]
@thornbill I think it's all good !  
If a want to add some new tests, can I refer to the same issue event if it is closed ?

**Comment by thornbill** [comment]
Yes, you can continue to reference the closed issue or just leave it blank. Either way is fine.

**Review by thornbill — APPROVED** [review]

**Pull request merged**
