### PR TITLE
Remove extraneous pageContainer element from videoOSD

### LINKED ISSUE #1786: Sliders become un-draggable after double click to fullscreen
**Describe The Bug**
After a double-click on the video to fullscreen, the OSD control sliders (both volume and playback position) work with single clicks along their length, but do *not* work with normal dragging "slider" functionality. The browser drags the OSD around instead.

**Steps To Reproduce**
1. Start a video
2. Adjust the sliders, watch them drag properly.
3. Double click the center of the screen to fullscreen
4. Attempt to drag the sliders again

**Expected Behavior**
Sliders to remain draggable

**Logs**
N/A

**Screenshots**

**System (please complete the following information):**
 - Platform: JF is running on a debian LXC under proxmox
 - Browser: Chrome  83.0.4103.116
 - Jellyfin Version: 10.6.2

**Additional Context**
Notably, this does not occur if I enter fullscreen via clicking the "fullscreen" button. I can also return the sliders to being functional after clicking empty space in the title bar.

I've noticed if I remove the `<div class="pageContainer flex"></div>` empty element, this behavior does not occur. I doubt that helps but hey.

### PR DESCRIPTION
**Pull request by bugfixin**
**Changes**
Removes the pageContainer element - there are some remaining references to pageContainer within styles, but that may be necessary for the pageContainer in the server selection page.

**Issues**
Fixes #1786

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
`videoosd.css` is only imported in `videoosd` controller. So `pageContainer` instances in `videoosd.css` can be removed.

**Comment by dkanada** [comment]
Should we backport this pull request?

**Comment by dmitrylyzo** [comment]
> Should we backport this pull request?

I think yes, but you have moved `videoosd.html`.

**Comment by dmitrylyzo** [comment]
I think these lines are safe to delete:
https://github.com/jellyfin/jellyfin-web/blob/7133294b8b8296c0b9b66d9f71cbc405b79b89e8/src/assets/css/videoosd.css#L10
https://github.com/jellyfin/jellyfin-web/blob/7133294b8b8296c0b9b66d9f71cbc405b79b89e8/src/assets/css/videoosd.css#L251-L255

**Comment by bugfixin** [comment]
Removed styles as well :) Regarding the backporting, is there anything I can do to make that easier?

**Pull request merged**
