### PR TITLE
Remove classlist shim

### PR DESCRIPTION
**Pull request by 3flex**
**Changes**
Remove the `classlist.js` dependency. Supported browsers natively support this now.

**Issues**

### CODE REVIEW

**Comment by 3flex** [comment]
Oh possibly. I did have a quick look at the Jellyfin docs which only mentioned browser support but not things like Tizen - but I didn't know what kind of support was offered there.

Is it documented anywhere? Or do they use old Chrome versions? Some old versions are listed in packages.json. Those all have support for this natively.

Maybe it's safer to leave it then, I understand embedded web browsers can be quite old, and without documentation it's hard to say if things would break.

**Comment by 3flex** [comment]
There's info on Tizen here: anything from Tizen 2 and up (2017 models and newer) will work because it uses Chromium 47+ and classlist support was added in 27: https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

Again without docs on supported environments and versions it's hard to say definitely.

**Comment by thornbill** [comment]
Supported browsers: https://github.com/jellyfin/jellyfin-web/blob/master/package.json#L139

The polyfill was added due to missing support for `classList.replace`: https://github.com/jellyfin/jellyfin-web/pull/967#discussion_r398918989

**Comment by 3flex** [comment]
Thanks, I'd found the browser list already but didn't realise that the specific method used would still need the polyfill. I'm guessing there are plenty of gaps in the test suite so I'll avoid this kind of PR in future.

Closing.

**Pull request closed without merging**
