### PR TITLE
Change primary highlight for delete confirmation dialog

### PR DESCRIPTION
**Pull request by grafixeyehero**
After
Screenshot (16)

**Issues**
Delete Media confirmation is highlighted the wrong way around #419

### CODE REVIEW

**Comment by dkanada** [comment]
There are exactly five instances of reversed behavior based on a quick search. @Cyan101 does that sound accurate? @grafixeyehero a better solution would be to remove the `primary` option and add a boolean to the options that will turn the primary option red, which is what we were talking about in the issue linked above.

**Comment by Cyan101** [comment]
sounds about right, I think the css classes for them should be swapped
around and can be left at that, but if you do want to add a red one can
perhaps just add another class but might have to change how the buttons are
generated

**Comment by dkanada** [comment]
@grafixeyehero your latest commit removes the submit functionality which we need to keep as an option. I can add something to keep both if you want.

**Comment by dkanada** [comment]
@anthonylavado I'd like to get three reviews here since we're modifying a destructive action. I haven't tested this but the logic should be fine.

**Pull request merged**
