### PR TITLE
Add configurable IgnoreDts flag to M3U tuner

### PR DESCRIPTION
**Pull request by knackebrot**
**Changes**
Added configurable IgnoreDts flag

Depends on https://github.com/jellyfin/jellyfin/pull/7903

**Issues**
Fixes https://github.com/jellyfin/jellyfin/issues/7267

### CODE REVIEW

**Comment by Bond-009** [comment]
This should target master (same as on server side)

**Comment by Bond-009** [comment]
Server side PR is now merged (to master)

**Review by thornbill — APPROVED** [review]

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by hjschmidt99** [comment]
hey @joshuaboniface , looks like there is still a review pending, preventing this issue from making it into a release.
Could you please take a look?
Many Thanks
Hans-Jürgen Schmidt

**Comment by thornbill** [comment]
No. This has been merged. It is a new feature though so it will not go in a release until a new feature release is made.

**Pull request merged**
