### PR TITLE
fix rounded progress bars

### PR DESCRIPTION
**Pull request by grafixeyehero**
Fix Rounded progress bars! https://github.com/jellyfin/jellyfin-web/issues/255

### CODE REVIEW

**Comment by grafixeyehero** [comment]
@dkanada i think this actulaly slove the problem, here  is the screen shot
Screenshot_2019-04-24 Jellyfin

Can you elaborate the issue that you meantioned in progress element used in audio and vedio so that it can be modified

**Comment by dkanada** [comment]
We are trying to go in the opposite direction though, no rounded edges in the main theme most of the time. I think most controls have slightly rounded edges but not this much. You could actually add this to the purple haze theme and it would look really good though, that one has a rounded style.

**Comment by grafixeyehero** [comment]
But Firefox was used that

`progress::-moz-progress-bar {
    border-radius: .4em;
    background-color: #00a4dc
}
`

**Comment by grafixeyehero** [comment]
Firefox 
Screenshot_2019-04-29 Jellyfin(3)

chrome
Screenshot

**Comment by grafixeyehero** [comment]
ahh this was the issue for **Chrome**
`progress::-webkit-progress-bar {
    background: #ccc
}`

this will fix it
`progress::-webkit-progress-bar {
    border-radius: .4em;
    background: #ccc
}`

**Comment by grafixeyehero** [comment]
As you say We are trying to go in the opposite direction though, no rounded edges in the main theme. I will remove it from the main themes and move it to purple haze theme

**Comment by grafixeyehero** [comment]
Screenshot (2)

**Pull request merged**
