### PR TITLE
Convert files to SCSS

### PR DESCRIPTION
**Pull request by GuilhermeHideki**
**Changes**
Convert some css files from `src/assets/css` to sass, reordering some elements and other small fixes.

**Issues**
Related to #836

### CODE REVIEW

**Comment by ferferga** [comment]
@GuilhermeHideki Could you fix conflicts so we can merge this?

Thanks!

**Comment by GuilhermeHideki** [comment]
@ferferga I will try in the weekend, if that's ok

**Comment by GuilhermeHideki** [comment]
@ferferga Done! Should I ping someone for review/approval?

**Review by ferferga — APPROVED** [review]
Don't worry, I'll do it @GuilhermeHideki

**Pull request merged**
