### PR TITLE
Use "Save" in Metadata Editor and remove "SaveChanges".

### PR DESCRIPTION
**Pull request by bluemoehre**
Unified/merged `Save` & `SaveChanges` translations.

**Changes**

- Merged both into `SaveChanges`
  - because this key was more recent in commit history
  - and is more accurate about the context
- Use of shortest value to prevent unnecessary line-breaks in UI & save space
- Double checked all translations with ChatGPT 4o 
  - should be common for a software context
  - and for saving or applying user input

**Issues**

#6211

### CODE REVIEW

**Comment by bluemoehre** [comment]
Technically, I have no problems with changing it back to `Save`, but the reasoning (above) still makes sense to me, especially if I compare all the rest of the keys.

> FYI, other languages should only be edited with Weblate to avoid conflicts.

It's a one-click in my IDE to convert everything. Will it cause problems that way?

**Comment by thornbill** [comment]
Yes it does cause issues, and we do not accept llm generated translations.

**Comment by bluemoehre** [comment]
> we do not accept llm generated translations.

It's not LLM generated translations! It's just checked by LLM because I didn't know if the older or newer version was the one to take. So it's just for everyone's assurance to not only rely on me. (Obviously fixing a long time bug which affects all language files is nothing easy without automation)

> Yes it does cause issues

How can I change this PR so we can get rid of the duplicates, without doing everything manually?

**Comment by dmitrylyzo** [comment]
> How can I change this PR so we can get rid of the duplicates, without doing everything manually?

Since we only need to narrow the text:
1. Revert all.
2. Change `SaveChanges` to `Save` in `src/components/metadataEditor/metadataEditor.template.html`.
3. Remove `SaveChanges` from `src/strings/en-us.json` (since it's no longer in use). Weblate will remove it from other languages.

**Comment by bluemoehre** [comment]
@dmitrylyzo done as you suggested. For DE it's fine. Native speakers of the respective languages (FR, PT, BU, etc.) must adapt their buttons themselves, then.

**Comment by thornbill** [comment]
Sorry for misunderstanding your GPT comment before.

Our weblate system will remove the translations in other languages once it is removed from the primary language. If the "Save" translation is problematic that would be concerning since it is already used in similar edit dialogs/screens.

**Review by dmitrylyzo — APPROVED** [review]
LGTM. Merge with squash.
I have changed the PR title, but it can be improved if necessary.

**Comment by bluemoehre** [comment]
Thanks everyone! 🙂👍

**Pull request merged**
