### PR TITLE
Trim username on login

### PR DESCRIPTION
**Pull request by FarisR99**
**Changes**
Trim the username before attempting to authenticate.

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I don't think this is a good change. The server technically supports usernames starting/ending with whitespace, this change would block the ability to sign into those accounts.

**Comment by FarisR99** [comment]
@nielsvanvelzen That's fair, I had this consideration in the back of my mind but I didn't confirm whether you *can* have whitespaces + assumed people wouldn't do something as weird as this. I do believe that in the first place, whitespaces before and after names should never be supported, but it is too late now.

The main problem with whitespaces I ran into was that autocomplete on Android would add a space after the completion so you have to backspace on this app, whereas on a typical app it will trim it.

**Comment by FarisR99** [comment]
An alternative solution would be for the backend to do a "best match" first taking into account whitespaces, but worst case matching stored usernames with spaces before/after to the input with no spaces. This is hacky though.

**Comment by thornbill** [comment]
Yeah I think this would need to be handled on the backend. We should probably be trimming usernames when they are created, but for backwards compatibility we would need to check both trimmed and untrimmed.

**Pull request closed without merging**
