### PR TITLE
Fix library filter state not being saved on client

### LINKED ISSUE #40: Library Filter Does Not Save At All
On the webapp (going to my jellyfin instance through a browser), when I use a filter on a library (filter by unplayed, specifically) it doesn't save its state. This issue existed in Emby, but didn't exist in the Android app. I'm going to try building the app again to see if I can reproduce this on the Jellyfin app.

EDIT: Can confirm that this issue exists with the app as well.

### PR DESCRIPTION
**Pull request by ricci2511**
**Changes**
Added saveQuery function calls on several `filterchange` event callbacks to properly save the filter state on the client.

**Issues**
Fixes #40

### CODE REVIEW

**Comment by ricci2511** [comment]
Maybe to avoid less repetition it would be worth it to abstract the `this.showFilterMenu` function callback to its own function, e.g. like this:

```
function showFilterMenuCb(query, mode, filterchangeCb) {
    import('../../components/filterdialog/filterdialog').then(({ default: filterDialogFactory }) => {
        const filterDialog = new filterDialogFactory({
            query,
            mode,
            serverId: ApiClient.serverId()
        });
        Events.on(filterDialog, 'filterchange', filterchangeCb);
        filterDialog.show();
    });
}
```

And then e.g. in `movies.js` we could replace the current `this.showFilterMenu` implementation with this:

```
    this.showFilterMenu = showFilterMenuCb.bind(this, query, 'movies', () => {
        query.StartIndex = 0;
        userSettings.saveQuerySettings(savedQueryKey, query);
        itemsContainer.refreshItems();
    });
```

**Comment by thornbill** [comment]
I have a concern with this... our current UI does not have any indication when a filter is active. I can see this causing an influx of issues where people have forgotten they set a filter and are confused why some of their content is not being displayed.

**Comment by ricci2511** [comment]
Understandable, I guess I could look into implementing such indicator if desired.

**Comment by thornbill** [comment]
This was implemented in https://github.com/jellyfin/jellyfin-web/pull/5717

**Pull request closed without merging**
