### PR TITLE
Add "AllowedTags" option to parental controls

### PR DESCRIPTION
**Pull request by Jpuc1143**
**Changes**
Adds an option in Parental Controls to only allow media with selected tags for viewing.

**Issues**
Client side configuration of jellyfin/jellyfin#9139

### CODE REVIEW

**Comment by xangelix** [comment]
Is the backend implemented as expected @Jpuc1143 ?

It seems unintuitive to require setting the tag on the library itself, and even then, the /Items request fails to list the tagged items. I am forced to provide the direct link to the item. Is there an additional metadata item which must be tagged for listing a library?

**Comment by Shadowghost** [comment]
@Jpuc1143 would be nice if you can rebase on master

**Comment by harri-clarke** [comment]
+1 as soon as this is added I can finally get migrated over from plex :)

**Comment by cutzenfriend** [comment]
Is this feature dead? Cause I need this too.... :(

**Comment by cutzenfriend** [comment]
+1 also from me. Urgently needed.

**Comment by nalroni** [comment]
Easily the most needed feature in jellyfin

**Comment by brutelxr** [comment]
Any timeframe when this will be released?

**Comment by thornbill** [comment]
[No](https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available). Additionally this change has not even been merged to master/unstable. This PR seems to have been abandoned by the original author and there are reports that the updated PR opened by someone else is not working as expected... so it still needs reviewed and additional testing.

**Comment by nalroni** [comment]
I wonder if the main dev team would consider picking this option up? It's a
critical tool for parental controls

**Comment by thornbill** [comment]
> I wonder if the main dev team would consider picking this option up?

Yes, I plan to make necessary changes to anything that I have tagged with the 10.9.0 milestone if the PR author does not address feedback or conflicts (which is the case for the updated PR). If the feature is not functioning as expected, that may require additional changes server side though.

**Comment by nalroni** [comment]
That's awesome! Thank you for the response and support.

**Comment by thornbill** [comment]
Superseded by #4535

**Pull request closed without merging**
