### PR TITLE
Fix mkv directplay on Edge chromium

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- add initial support for Edge chromium.
- mark mkv as supported in Edge chromium. (It reports that it is unsupported but it actually does just like edgeUwp)
- H.265 directplay requires the extension from microsoft store and a capable GPU. (software playback is unsupported)

**Notes**
edg -> edge chromium on Windows or macOS
edga -> edge chromium on Android
edgios -> edge chromium on iOS

**Issues**
https://github.com/jellyfin/jellyfin-web/issues/1631

edgechromium

### CODE REVIEW

**Comment by nyanmisaka** [comment]
Not sure if mkv is also supported on Edge chromium macOS.

**Comment by ThibaultNocchi** [comment]
Should #1631 be closed then?

**Comment by MrTimscampi** [comment]
> Should #1631 be closed then?

If someone can confirm that it works, then yes :)

This hit 10.6.1 so the fix is in the latest release (from last night)

**Comment by ThibaultNocchi** [comment]
Ok then I'll test this evening if no one has done it

**Comment by johnvick** [comment]
I still get Edge browser transcoding 10 bit HEVC on Jelly 10.6.1 whereas on 10.5.5 it played directly. I have the Microsoft HEVC addon installed.

**Comment by josersanchez0117** [comment]
Here's the free HEVC codec. [https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab](https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab
)
Also, I tested it and it does work. HEVC Main 10 direct plays with no problems.

**Comment by johnvick** [comment]
Tried this again on three computers - Surface Book 2 i5, AMD Ryzen + Nvidia 1660 and AMD Ryzen with APU. The conclusion is that some HEVC 10 bit play directly and some don't - the ones that don't (on my limited testing) have DTS soundtracks and the ones that do have AAC 2 channel.

**Comment by nyanmisaka** [comment]
> Tried this again on three computers - Surface Book 2 i5, AMD Ryzen + Nvidia 1660 and AMD Ryzen with APU. The conclusion is that some HEVC 10 bit play directly and some don't - the ones that don't (on my limited testing) have DTS soundtracks and the ones that do have AAC 2 channel.

Edge chromium doesn't support DTS which should result in transcoding.

**Pull request merged**
