### PR TITLE
Replacing Elements

### PR DESCRIPTION
**Pull request by grafixeyehero**
continued form Convert emby-button and emby-scroller to react #4173

### CODE REVIEW

**Comment by thornbill** [comment]
Hey @grafixeyehero any chance you will have time to work on this again soon? There are some merge conflicts and some lint issues that need cleaned up. (We added some more lint rules to catch things sonar was flagging as issues since this was originally opened.) Thanks!

**Comment by grafixeyehero** [comment]
> Hey @grafixeyehero any chance you will have time to work on this again soon? There are some merge conflicts and some lint issues that need cleaned up. (We added some more lint rules to catch things sonar was flagging as issues since this was originally opened.) Thanks!

@thornbill before i continue on this you may see this (https://github.com/grafixeyehero/jellyfin-web/tree/replace-viewitemcontainer-api)

**Comment by thornbill** [comment]
Oh that looks very promising @grafixeyehero. Have you done any testing with TV mode yet? I added the "experimental" layout so I could avoid dealing with that for now in my work with mui. :sweat_smile: 

We may need to work out a good solution for the future of the TV mode sooner than planned so we aren't constantly blocked by that.

**Comment by grafixeyehero** [comment]
@thornbill for tv mode I didn't test it yet.
I agree with you. First let revert asyncRoutes to legacyRoutes then use the experimental PR as a base for migration.

**Comment by thornbill** [comment]
Yeah I think that sounds good! 🤘

**Pull request closed without merging**
