### PR TITLE
Remote sessions support for SyncPlay

### PR DESCRIPTION
**Pull request by OancaAndrei**
**Changes**
Add remote player support to SyncPlay.

This PR is related to the [server side one](https://github.com/jellyfin/jellyfin/pull/4721).

### CODE REVIEW

**Comment by OancaAndrei** [comment]
Needs more testing. Also, *remote session control* looks broken to me when **not** enabling SyncPlay.

**Comment by dkanada** [comment]
@OancaAndrei I'm not sure if it was fixed recently, but it was indeed broken for a while.

**Comment by OancaAndrei** [comment]
Lol, what happened to `yarn`?

**Comment by dmitrylyzo** [comment]
> Lol, what happened to `yarn`?

We are using `npm` now.

**Pull request closed without merging**
