### PR TITLE
make itembackrop full screen width

### PR DESCRIPTION
**Pull request by grafixeyehero**
changes:
move detiallogo to pagetitle
make itembackdrop full screen width
add itembakropfader for styling the backdrop gradient
remove backrop from detailpage

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Would it be possible to add a background color to the title/controls bar when scrolling ?

image

Readability of text on light backdrops is also somewhat an issue. Adding a 0 0 2px black text-shadow to detailPageWrapperContainer helps, but it looks a bit iffy.

image

Not too sure what a proper fix would be, other than darkening the gradient.

**Comment by grafixeyehero** [comment]
Annotation 2020-02-26 213w720

**Comment by grafixeyehero** [comment]
Annotation 2020-02-27 022w636

**Comment by dkanada** [comment]
This conflicts somewhat with #823, you guys should decide on a final style together.

**Comment by grafixeyehero** [comment]
> 
> 
> This conflicts somewhat with #823, you guys should decide on a final style together.

@MrTimscampi it's your decision

**Comment by MrTimscampi** [comment]
> > This conflicts somewhat with #823, you guys should decide on a final style together.
> 
> @MrTimscampi it's your decision

If this screenshot is okay with you, mine is pretty much ready to merge after I fixed a few oddities on the noBackdrop version:

image

**Comment by grafixeyehero** [comment]
closed in a favor of #823

**Pull request closed without merging**
