### PR TITLE
Don’t set save lyrics locally as default

### PR DESCRIPTION
**Pull request by gnattu**
This option requires write permission to the media folder which should not be enabled by default.

**Changes**

**Issues**

See jellyfin/jellyfin#11523

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
Shouldn't we do the same with subtitles?

**Comment by gnattu** [comment]
I think we should, but niels does not agree as we are saving subtitles with media as default for years.

**Comment by Shadowghost** [comment]
I'd still argue that for consistency's sake we should set both to the same value

**Comment by thornbill** [comment]
If the defaults need changed that discussion should happen on the server side. This PR only updates web to align with the server values.

**Pull request merged**
