### PR TITLE
Images on Plugins

### PR DESCRIPTION
**Pull request by BaronGreenback**
Uses Plugins/{id}/Image api.

Depends on: https://github.com/jellyfin/jellyfin/pull/4583

### CODE REVIEW

**Comment by Artiume** [comment]
Could the plugins provide their own images? Doesn't look like third party repo's could supply their own images in this way.

**Comment by dkanada** [comment]
The images are basically proxied through the server, they aren't actually stored there.

**Comment by h1dden-da3m0n** [comment]
aren't the changes in this PR already superseded by or more accurately included in jellyfin-web#2225?

**Comment by BaronGreenback** [comment]
> aren't the changes in this PR already superseded by or more accurately included in #2225?

Yes it is - sorry - will close this one.

**Pull request closed without merging**
