### PR TITLE
fix: notched devices area not covered

### PR DESCRIPTION
**Pull request by ferferga**
### ~~Untested yet~~

~~Should fix jellyfin/jellyfin-android#289~~

Read https://github.com/jellyfin/jellyfin-web/pull/2356#issuecomment-768377889, https://github.com/jellyfin/jellyfin-web/pull/2356#issuecomment-768400058 and https://github.com/jellyfin/jellyfin-web/pull/2356#issuecomment-772606784

### CODE REVIEW

**Comment by MrTimscampi** [comment]
Wouldn't this lead to cut videos? (As in the notch area will be used like normal screen real estate, leading to the video appearing behind the notch)

**Comment by ferferga** [comment]
@MrTimscampi This will work only when aspect ratio in the playback settings is set to "Cover". By default it's contain, which crops borders at the right and at the left. That *should* be unaffected.

**Comment by nielsvanvelzen** [comment]
This value will be ignored by the custom webview implementation in the Android app.

**Comment by ferferga** [comment]
I will test if it makes a difference for mobile browsers and, if it doesn't, I'll close this.

**Comment by Maxr1998** [comment]
See my comment in jellyfin/jellyfin-android#289, the webview padding is determined by the app, the wrong color was a bug in the app and is already fixed.

**Comment by ferferga** [comment]
@Maxr1998 I saw it already :)

The thing is that, if I'm using Edge or Chrome in my phone (not the app) the notch area is still not 100% covered and this might fix that.

That's what I want to verify 👍🏻

**Comment by ferferga** [comment]
@nielsvanvelzen @Maxr1998 @MrTimscampi This does indeed allows the video to take notch area in the web client in an Huawei P30 with Firefox, so I think this is good to have 👍.

**Review by nielsvanvelzen — APPROVED** [review]

**Review by dkanada — APPROVED** [review]

**Pull request merged**
