### PR TITLE
Using nullish operator instead of logical OR

### PR DESCRIPTION
**Pull request by Goku-04**
**Changes**
* Using nullish operator (??)  instead of logical OR (||)

**Issues**
N/A

<sub>This is my first PR in a major repository and first PR under hacktoberfest and I am not good in typescript so kindly guide me if this raises any issue :pray: </sub>

### CODE REVIEW

**Comment by ferferga** [comment]
@Goku-04 LGTM and I'm in favor of this change, but why only in this place? What about the other places where it could be replaced?

**Comment by Goku-04** [comment]
Sure. Tommorow I will look up other parts where this can be done and mention you upon required updation. 👍

**Comment by Goku-04** [comment]
@ferferga  completed the job 🫡

**Comment by dmitrylyzo** [comment]
Nullish operator produces more code after transpilation (for legacy browsers) and is mostly unnecessary. I think it should only be used when the left part could be (by design) a falsey value.

**Comment by Goku-04** [comment]
> Nullish operator produces more code after transpilation (for legacy browsers) and is mostly unnecessary. I think it should only be used when the left part could be (by design) a falsey value.
I read a bit about transpilation right now and I concur it will produce some extra code.

**Comment by Goku-04** [comment]
Should I close this PR? or leave it up for any discussion?

**Comment by thornbill** [comment]
I think it can be closed now. Sorry for the back and forth on this one. I have disabled the rule in sonar so those errors should go away after the next push to master.

**Pull request closed without merging**
