### PR TITLE
Filter videos by audio stream language

### PR DESCRIPTION
**Pull request by taconaut**
Uses and exposes the audio language filtering being added with this PR: https://github.com/jellyfin/jellyfin/pull/624

It currently looks like this:
image

### CODE REVIEW

**Comment by taconaut** [comment]
@dkanada unfortunately not, I'm a mainlya backend guy. It would be handy to have a fallback onto a default language, probably en-US.

**Comment by taconaut** [comment]
It would be nice to also localize the language code.
Does the backend have any localization so it could return a tuple containing the language code along with the localized language name? Or is everything done in the frontend? (I'm dicovering the project ;)

**Comment by dkanada** [comment]
> Does the backend have any localization so it could return a tuple containing the language code along with the localized language name? Or is everything done in the frontend?

We have some very basic localization in the frontend, no clue about the backend. There must be some code somewhere to get the language name because I have seen it in a couple of locations in the server dashboard. One location is Dashboard -> Library -> Metadata -> Language if you want to do some digging. It would definitely be better to show the language name instead of the language code here.

**Comment by Oliver-Hanikel** [comment]
I'm a bit confused. The PR was merged but I can't find the language option on my Jellyfin 10.6.4.
image

**Comment by dkanada** [comment]
We had to revert this because the backend portion was never finished.

**Pull request merged**
