### PR TITLE
Dashboard Styling Bug fixes (add library text cut off, css textbox, and too long last seen text)

### LINKED ISSUE #1051: "Add Media Library" text cut off at smaller window widths
**Describe the bug**
Smaller window sizes result in the "Add Media Library" button having its text misaligned

**To Reproduce**

1. Go to 'Libraries'
2. Shrink the window

**Expected behavior**
Add Media Library button should always have its text fully visible

**Screenshots**
Can vary in how bad it is, here are two examples:
Screen Shot 2020-04-09 at 12 26 11 AM
Screen Shot 2020-04-09 at 12 27 01 AM

**System (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.2

### LINKED ISSUE #1490: 10.6.0 dashboard users - last seen text is too long
**Describe the bug**
From the dashboard then users, the text "last seen" is too long to be shown or the area text is too short

**Screenshots**

image
image

**System (please complete the following information):**
 - Browser: Chrome
 - Jellyfin Version: 10.6.0

### PR DESCRIPTION
**Pull request by Influence365**
Fixes a few UI bugs

**Changes**
See Below Images (old on left, new on right)

2020-07-09-fix-add-library-text
Moved 'add new library' to footer

2020-07-09-fix-css-input
Removed ability to change size of text input since it already automatically adjust to the input.

2020-07-09-fix-too-long-recently-seen
Allowed text to wrap around so all info can be seen

**Issues**
fixes #1490
fixes #1051

### CODE REVIEW

**Comment by dkanada** [comment]
That last one is questionable, we avoided wrapping text on the media card because it was causing inconsistent vertical spacing and an odd look. It sounds fine as a fix for now but we should consider alternate methods for the future.

**Comment by Influence365** [comment]
Yeah that's a good point, we could do:
`.localUsers .cardText-secondary {
height: 3em;
}` in dashboard.css.

which would allow for the text to be on two lines, fixing the issue while also keeping all card heights and vertical spacing the same

**Comment by dkanada** [comment]
That sounds like a good fix for now. We can probably also fit this in 10.6.0 since it's a minor code change.

**Comment by Influence365** [comment]
Ok thanks, I'll fix it now

**Comment by Shadowghost** [comment]
In German the Last Seen text (e.g. the translation of "last seen less than a minute ago") can be 3 lines long. You can see that the text is wrapped to the next line and you can select it - it's just outside the visible box.

**Comment by Influence365** [comment]
Thanks for noticing that. I think that I will probably have to adjust the width of the cards because adding a third row might look a bit strange.

**Pull request merged**
