### PR TITLE
Rename Mixed Content and TV Shows

### PR DESCRIPTION
**Pull request by Artiume**
**Changes**

**Issues**

### CODE REVIEW

**Comment by Artiume** [comment]
This should probably be done via Weblate ctually.

**Comment by dkanada** [comment]
If we're making this change, I propose we also rename TV Shows to Shows for a slightly more generic term. If we don't make this change then disregard my comment.

**Comment by Artiume** [comment]
Renamed TV Shows to Shows

**Comment by thornbill** [comment]
“Custom” just seems so ambiguous. I believe that type is for unorganized combinations of tv shows and movies because it still scrapes metadata right?

I seem to recall you being vetoed on the “shows” change in the past @dkanada. Although I don’t personally have a preference on that one.

**Comment by dkanada** [comment]
I was at the time because users were confused with the change, but if we're apparently renaming mixed content I figured I'd bring it up again.

**Comment by Artiume** [comment]
Mixed Content's current job as mixing tv shows and movies doesnt work well and there's no real plans for us to fix the regex to make it perfect. I think Custom is a better approach because it's the actual intent of the Library, I do think we should change the metadata grabbers default to off so that you can enable them if you want, but they're OFF because they're not the real intent. It'll make more sense once we have additional metadata grabbers like YouTube and such.

**Pull request closed without merging**
