### PR TITLE
Fix padding in header

### PR DESCRIPTION
**Pull request by dannymichel**
**Changes**

**Issues**

### CODE REVIEW

**Comment by dannymichel** [comment]
fix

**Comment by MrTimscampi** [comment]
The screenshot seems to be the same as in #759 , what are the differences between the two PRs ?

**Comment by Shadowghost** [comment]
One for the header text and the other for the logo

**Comment by MrTimscampi** [comment]
The text is intended to be level with the icons, though (Everything should be centered vertically).

Do also note that #737 already fixes the padding and margins around the headerbar element, aside from the logo fixed in #759 .

Here's how it currently looks:

image

**Pull request merged**
