### PR TITLE
Removed all legacy Emby CSS

### PR DESCRIPTION
**Pull request by Ben-Wallner**
**Changes**

I removed all legacy Emby CSS naming to clean up the code

**Issues**

none

### CODE REVIEW

**Comment by cvium** [comment]
What is the benefit to this exactly? It's a humongous PR.

**Review by oddstr13 — CHANGES_REQUESTED** [review]
This will cause a massive amount of work in *all* plugins that utilizes the web pages.

There are about 300 lines with `emby-` in them in the currently active official plugins alone, and this is very likely to also affect *all* unofficial plugins.

**Comment by MrTimscampi** [comment]
Marking for discussion, as this is a potentially contentious change.

Not only does it break all the plugins (First and third party) but it can also very easily lead to issues in the client, requiring ideally an entire cycle to test and validate.

**Comment by thornbill** [comment]
Closing based on points above.

**Pull request closed without merging**
