### PR TITLE
Fix redirect after deleting item

### LINKED ISSUE #1038: Deleting season jumps back to home screen
**Describe the bug**
Deleting a show season jumps back to Home.

**To Reproduce**

1. Go to a show with multiple seasons, one of which you want to delete.
2. From the list of seasons, delete a seaon.
3. Observe how you are taken back to the user's Jellyfin Home screen.

**Expected behavior**
The season should disappear and I should stay in the show overview, where I can see remaining seasons, or delete them, etc.

**System (please complete the following information):**
 - OS: Fedora 31
 - Browser: Chrome
 - Jellyfin Version: 10.5.1

### PR DESCRIPTION
**Pull request by DrWarpMan**
**Changes**
Deleting an item (episode, season, ..) will now redirect to the parent of that item instead of redirecting to homepage.

_I wonder why is this behavior disabled in the first place and why it hasn't been changed/looked at in almost 8 years,
since it was [added](https://github.com/jellyfin/jellyfin-web/blob/ef8dbee498c84797710ed4ba2c218380f77e1155/dashboard-ui/bower_components/emby-webcomponents/itemcontextmenu.js#L585) (https://github.com/jellyfin/jellyfin-web/commit/ef8dbee498c84797710ed4ba2c218380f77e1155). Or am I missing something?_

**Issues**
Fixes #1038

### CODE REVIEW

**Comment by thornbill** [comment]
This context menu is used all over the place and in most cases this would not be the desired behavior.  i.e. Deleting an item on the home page.

**Comment by DrWarpMan** [comment]
> This context menu is used all over the place and in most cases this would not be the desired behavior. i.e. Deleting an item on the home page.

I see, so what changes would you propose then? 
Would route checks be enough / good idea?

**Comment by thornbill** [comment]
Looks like it would be better to just change the behavior here: https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/itemDetails/index.js#L2024

**Comment by DrWarpMan** [comment]
I added the logic there, would you say it's ok now? @thornbill

**Review by thornbill — APPROVED** [review]
:+1: lgtm

**Comment by brianjmurrell** [comment]
Nice to see this finally fixed.  Awesome job @DrWarpMan!

**Pull request merged**
