### PR TITLE
Fix movies Shuffle button

### PR DESCRIPTION
**Pull request by davidmurdoch**
The Movies `Shuffle` button doesn't do anything anymore, as `topParentId` is `undefined`, which isn't permitted by `ApiClient.getItem`. I've fixed it by using the `SortBy: Random` query option and now pick the first item from the list that it returns.

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
Checked the unstable (8ffe7fec2feeb334c867c9eb477fa1678238b317): `topParentId` is the id of the library, and shuffle works (unless a bad item is caught). :man_shrugging:

**Comment by davidmurdoch** [comment]
@dmitrylyzo I did as well. `topParentId` was always `undefined`.  🤔

**Comment by thornbill** [comment]
Do you happen to be using an extension like clear urls that mangles url parameters? That has been an issue that has came up in the past.

**Comment by 1hitsong** [comment]
Like others, I'm unable to recreate this issue. Shuffle in the context menu starts playing a shuffled playlist of my movies.

**Pull request closed without merging**
