### PR TITLE
Fixing Border radius and light theme improvements

### PR DESCRIPTION
**Pull request by Influence365**
A range of theme based fixes, including:

- fixing border radius with the addition of blur hash

- light theme changes to improve readability

**Changes**
See Below Screenshots

Scroll Arrows (light theme)
2020-07-06-fix-light-mode-scroll-arrows
List Seperation (light theme)
2020-07-06-fix-light-mode-list-seperation
Border Radius (Purple Haze)
2020-07-06-fix-border-radius-1
Border Radius (Apple TV)
2020-07-06-fix-border-radius-2

### CODE REVIEW

**Comment by Influence365** [comment]
> The screenshots look really nice!

Thanks! The posters are from: 

https://www.reddit.com/r/jellyfin/comments/gleugo/its_spring_time_again_and_the_exams_are_closing/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by dmitrylyzo** [comment]
Border radius here is border + card border radius, i.e. should be `1.3em`
https://github.com/jellyfin/jellyfin-web/blob/242413ab18a792fe3b932401fbfc11afdad5431e/src/themes/purplehaze/theme.css#L566

**Comment by Influence365** [comment]
Are you saying that I need to add a border radius to `cardScalable`, because from what I can tell, changing it has no visual effect since it has no background colour and all child components have the `border-radius` property applied.

**Comment by dmitrylyzo** [comment]
> because from what I can tell, changing it has no visual effect since it has no background colour and all child components have the border-radius property applied.

You need "slow" browser mode.

To activate "slow" browser mode, activate Device Mode in browser and set user agent to some SmartTV.
For example, `Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/56.0.2924.0 TV Safari/537.36`

You need a full block (with trimmed value) https://github.com/jellyfin/jellyfin-web/blob/242413ab18a792fe3b932401fbfc11afdad5431e/src/themes/purplehaze/theme.css#L564-L567

**Comment by Influence365** [comment]
OK, thanks for explaining that, I have fixed the issue on Apple TV, the problem is not present on purple haze (the only other theme with round corners)

**Comment by dmitrylyzo** [comment]
> the problem is not present on purple haze (the only other theme with round corners)

On Purple Haze, border has become uneven - need to change value to `1.3em`:
https://github.com/jellyfin/jellyfin-web/blob/242413ab18a792fe3b932401fbfc11afdad5431e/src/themes/purplehaze/theme.css#L566
<details>
<summary>Where does `1.3em` come from?</summary>

Sum of
https://github.com/jellyfin/jellyfin-web/blob/df0f266ef0503e2473e8f157b7e40ac40766205f/src/components/cardbuilder/card.css#L112
https://github.com/jellyfin/jellyfin-web/blob/df0f266ef0503e2473e8f157b7e40ac40766205f/src/themes/purplehaze/theme.css#L202
_or other `0.8em`_
</details>

> Should I create another PR with the changes?

Yes, this PR is merged.

**Comment by Influence365** [comment]
Thanks a bunch for your help. I'll do it now

**Pull request merged**
