### PR TITLE
Show hamburger menu on mobile and fix title padding

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Fix title padding on mobile and shows the hamburger menu icon even on mobile.

**Issues**

### CODE REVIEW

**Comment by hamburglar2160** [comment]
With the hamburger menu visible on all interfaces the Home button can be hidden/removed as that button is present in the top of the menu.

**Comment by dkanada** [comment]
We might want to remove the icon for mobile layouts when the hamburger menu is visible.

**Comment by MrTimscampi** [comment]
> We might want to remove the icon for mobile layouts when the hamburger menu is visible.

Which icon ?

**Comment by dkanada** [comment]
The project logo and name, which both take up a lot of space on the header.

**Comment by MrTimscampi** [comment]
This is what it looks like on the smallest phone available in Firefox:

image

I think it looks fine for now, but I'm open to having only the icon without "Jellyfin" if needed.

**Comment by dkanada** [comment]
What does this look like on other pages that would normally include a back button and home button?

**Comment by MrTimscampi** [comment]
It's a little janky on regular screens:

image

I'd probably remove the home button (There isn't a lot of UI depth anyway) and hide the hamburger on screens other than home, like most mobile apps do.

**Comment by dkanada** [comment]
@MrTimscampi that sounds fine to me. I'm not sure it will be ideal but let's test it out and see what it feels like.

**Pull request merged**
