### PR TITLE
Make the default card colors look less like rainbow vomit

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Significantly improves the default card colors for most themes.

**Issues**

### CODE REVIEW

**Comment by Artiume** [comment]
Simple fix but can i get a before/after snapshot?

**Comment by MrTimscampi** [comment]
**Dark**

Before
image

After
image

**Blue Radiance**

Before
image

After
image

**Purple Haze**
Before
image

After
image

I'm more of a fan of the Dark one, but I figured I should at least try one for the two most used non-default themes.

**Comment by Artiume** [comment]
I'm not sure how I like the purple haze

**Comment by MrTimscampi** [comment]
> We have 5 different colors for each theme but it seems that we only have two or three :P

There actually 5 in the new color scheme. The issue is that having them be random colors look bad, so I kept it to generally accepted color harmonies. It sort of limits the amount of variation, but we do still have 5 colors for each (though not all are visible in my screenshots)

**Pull request merged**
