### PR TITLE
Fix subtitle display from previous file in queue

### LINKED ISSUE #518: Next file in queue displays subtitles from previous file
<details>
<summary>
Media Info of the file
</summary>
General
Unique ID                                : 57738582199882456715555624629367044167 (0x2B700BE386AA1C595A3743DFB12D7847)
Complete name                            : /nas/public/tv/Barry/Season 01/Barry - S01E05 - Chapter Five- Do Your Job WEBDL-1080p Proper.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.77 GiB
Duration                                 : 30 min 48 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 8 212 kb/s
Encoded date                             : UTC 2018-04-23 11:33:15
Writing application                      : mkvmerge v19.0.0 ('Brave Captain') 64-bit
Writing library                          : libebml v1.3.5 + libmatroska v1.4.8

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 30 min 47 s
Bit rate mode                            : Variable
Bit rate                                 : 7 575 kb/s
Maximum bit rate                         : 15.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.152
Stream size                              : 1.63 GiB (92%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 30 min 47 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 10 ms
Stream size                              : 141 MiB (8%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text jellyfin/jellyfin#1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 30 min 44 s
Bit rate                                 : 84 b/s
Count of elements                        : 579
Stream size                              : 19.0 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Text jellyfin/jellyfin#2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 30 min 44 s
Bit rate                                 : 92 b/s
Count of elements                        : 618
Stream size                              : 20.8 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No
</details>

<details>
<summary>
Logs
</summary>
[17:57:09] [INF] Deleting partial stream file(s) /transcode/transcodes/transcodes/transcodes/transcodes/a379bbd808371a28d0c508974af853ac.m3u8
[17:57:09] [INF] User policy for username. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[17:57:09] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:09] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:09] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:09] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:09] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:09] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:09] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -noaccurate_seek -f matroska,webm -i file:"/data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6 -segment_time_delta 0.021 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/transcodes/transcodes/transcodes/transcodes/ba5e20850a221f8b57a55a00da2a7bbc.m3u8" -y "/transcode/transcodes/transcodes/transcodes/transcodes/ba5e20850a221f8b57a55a00da2a7bbc%d.ts"
[17:57:09] [INF] returning /transcode/transcodes/transcodes/transcodes/transcodes/ba5e20850a221f8b57a55a00da2a7bbc0.ts
[17:57:10] [INF] Playback Started
[17:57:10] [INF] Stopping ffmpeg process with q command for /transcode/transcodes/transcodes/transcodes/transcodes/ba5e20850a221f8b57a55a00da2a7bbc.m3u8
[17:57:10] [INF] User policy for username. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[17:57:10] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:10] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv
[17:57:10] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:10] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv
[17:57:10] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:10] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv
[17:57:10] [INF] FFMpeg exited with code 0
[17:57:10] [INF] Deleting partial stream file(s) /transcode/transcodes/transcodes/transcodes/transcodes/ba5e20850a221f8b57a55a00da2a7bbc.m3u8
[17:57:10] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -noaccurate_seek -f matroska,webm -i file:"/data/tvshows/Barry/Season 01/Barry - S01E07 - Chapter Seven- Loud, Fast, and Keep Going WEBDL-1080p Proper.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6 -segment_time_delta 0.021 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/transcodes/transcodes/transcodes/transcodes/a96a8de3b5ca3dd87d7fcd9a834d6a01.m3u8" -y "/transcode/transcodes/transcodes/transcodes/transcodes/a96a8de3b5ca3dd87d7fcd9a834d6a01%d.ts"
[17:57:11] [INF] returning /transcode/transcodes/transcodes/transcodes/transcodes/a96a8de3b5ca3dd87d7fcd9a834d6a010.ts
[17:57:11] [INF] Playback stopped reported by app Jellyfin Web 10.4.0 playing Chapter Seven: Loud, Fast, and Keep Going. Stopped at 7444 ms
[17:57:11] [INF] Playback Stopped
[17:57:11] [WRN] HTTP Response 204 to 192.168.0.1. Time (slow): 0:00:01.7421135. http://example.com/Sessions/Playing/Stopped
[17:57:11] [INF] Item Not fully played. Tell trakt.tv we are no longer watching but don't scrobble
[17:57:11] [INF] Playback Started
[17:57:12] [INF] Playback stopped reported by app Jellyfin Web 10.4.0 playing Chapter Eight: Know Your Truth. Stopped at 382 ms
[17:57:12] [INF] Playback Stopped
[17:57:12] [WRN] HTTP Response 204 to 192.168.0.1. Time (slow): 0:00:01.5967539. http://example.com/Sessions/Playing/Stopped
[17:57:12] [INF] Item Not fully played. Tell trakt.tv we are no longer watching but don't scrobble
[17:57:14] [INF] Stopping ffmpeg process with q command for /transcode/transcodes/transcodes/transcodes/transcodes/a96a8de3b5ca3dd87d7fcd9a834d6a01.m3u8
[17:57:14] [INF] User policy for username. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[17:57:14] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:14] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:14] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:14] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:14] [INF] Profile: Unknown Profile, Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:57:14] [INF] Profile: Unknown Profile, No direct play profiles found for Path: /data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv
[17:57:14] [INF] FFMpeg exited with code 0
[17:57:14] [INF] Deleting partial stream file(s) /transcode/transcodes/transcodes/transcodes/transcodes/a96a8de3b5ca3dd87d7fcd9a834d6a01.m3u8
[17:57:14] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -noaccurate_seek -f matroska,webm -i file:"/data/tvshows/Barry/Season 01/Barry - S01E08 - Chapter Eight- Know Your Truth WEBDL-1080p Proper.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6 -segment_time_delta 0.021 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/transcodes/transcodes/transcodes/transcodes/935cc436340a0e27c53329c36cecce17.m3u8" -y "/transcode/transcodes/transcodes/transcodes/transcodes/935cc436340a0e27c53329c36cecce17%d.ts"
[17:57:14] [INF] returning /transcode/transcodes/transcodes/transcodes/transcodes/935cc436340a0e27c53329c36cecce170.ts
[17:57:14] [INF] Playback Started
[17:57:15] [INF] Playback stopped reported by app Jellyfin Web 10.4.0 playing Chapter Seven: Loud, Fast, and Keep Going. Stopped at 2637 ms
</details>

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: e.g. 10.4.0
 - Hardware settings & device: Tested with no transcoding, AMD AMF and VAAPI on Ryzen 2200G
 - Reverse proxy: haproxy
 - Other hardware notes: none
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10 and Arch Linux
 - Client: Browser
 - Browser (if Web client): Brave & Firefox
 - Client and Browser Version: 0.69.132 and 69.0.2

Since I upgraded to 10.4.0 I'm having an issue where if I'm watching a video with subtitles and when finished, move to the next one, the next one will display the subtitles of the first one. It happens every time, with both embedded subtitles and separate .srt files and with multiple languages. The only workaround is to simply exit the player and start playing the new file again from the dashboard.

I've tried restarting the container, rebooting the host, different series and files, different transcoding setups but I keep running into this issue.

### PR DESCRIPTION
**Pull request by dhartung**
Fixes #518

Working with the trackCueObject/TrackText-API is awful: There is a function `addTextTrack` but there is none to remove a textTrack afterwards. 
I think in the long run it's best to avoid using the texttracks API (see also #463 where other methods are mentioned), but for now this fix should work.

### CODE REVIEW

**Comment by JustAMan** [comment]
This seems to be doing somewhat similar to what https://github.com/jellyfin/jellyfin-web/pull/507 does, can you compare those?

**Comment by dhartung** [comment]
PR #507 adresses the offset/time-correction of the subtitles. This PR adresses #518 where Subtitles werent deleted when the src of the video changes, e.g. when switching to the next episode in a TV show.

**Comment by dkanada** [comment]
@dhartung there was another merge conflict so reverted your last merge resolution commit. Could you rebase the changes this time to keep the master branch history clean of merge commits?

**Comment by joshuaboniface** [comment]
Cherry-picked into 10.4.1.

**Pull request merged**
