### PR TITLE
Clean translations strings

### PR DESCRIPTION
**Pull request by sarab97**
**Changes**
Remove the unused keys which are not in en-us and not used in codebase

**Keys removed**
- DefaultCameraUploadPathHelp
- HeaderCameraUpload
- HeaderCameraUploadHelp
- LabelCameraUploadPath
- LabelCameraUploadPathHelp
- SelectCameraUploadServers
- AllowSeasonalThemes
- AllowSeasonalThemesHelp
- LabelDownloadInternetMetadataHelp
- LabelDeinterlacingMethod
- LabelWindowBackgroundColor
- MessageLoggedOutParentalControl
- MessageNoDownloadsFound
- OptionActors
- OptionMenu
- PlayOnAnotherDevice
- VideoResolutionNotSupported
- HeaderSource
- HeaderSplitMedia
- HeaderSubtitles
- LabelAddedOnDate

**Issues**
#1247

### CODE REVIEW

**Comment by dkanada** [comment]
#1246 is relevant here

**Comment by sarab97** [comment]
> #1246 is relevant here

oops didnt noticed that it wasnt mentioned on issue page

**Comment by MrTimscampi** [comment]
@sarab97 Can you rebase on master to clean up this branch?

**Comment by sarab97** [comment]
> @sarab97 Can you rebase on master to clean up this branch?

will require some assistance

**Comment by dkanada** [comment]
@sarab97 the merge issues have been fixed in another pull request so we'll close this one and track progress over there.

**Pull request closed without merging**
