### PR TITLE
Fix: prevent some backdrops from showing on homepage

### PR DESCRIPTION
**Pull request by acvigue**
**Changes**
prevents backdrops from items with an OfficialRating > TV-MA from showing when no ParentId given

**Issues**
None

### CODE REVIEW

**Comment by dkanada** [comment]
Does this affect backdrops when nothing in the library has ratings?

**Comment by acvigue** [comment]
@dkanada No, it does not. If an item has no rating, it will still be included.

**Comment by MrTimscampi** [comment]
I'd even put a lower rating than TV-MA.

Also, some questions:

* How does that work for non-US ratings? How does it handle stuff like France's "12+" or other countries' rating systems?
* How does that work for non-TV US ratings? Afaik, TV-MA is specific to the US and to TV shows. How does this handle rated-R movies?

**Comment by acvigue** [comment]
I would assume it follows the order shown in the chart when editing metadata within Jellyfin.
image

TV-MA is technically _above_ the rating of rated-R movies, so those backdrops are still shown.

**Comment by thornbill** [comment]
I wonder if this should use something lower like "TV-14"?

**Comment by MrTimscampi** [comment]
> I wonder if this should use something lower like "TV-14"?

I would probably go PG-13 for safety? TV-14 could still have blood and such, which some parents wouldn't like.

PG-13, on the other hand, is usually more about language, so that would be safer.

**Comment by acvigue** [comment]
Thanks for the input, i switched it to be PG-13

**Review by thornbill — APPROVED** [review]
:+1: Works as expected in my testing.

**Pull request merged**
