### PR TITLE
Small redesign to some plugin pages

### PR DESCRIPTION
**Pull request by Camc314**
Redesign of plugin cards to better use space especially on mobile

**Changes**
<details>
<summary>Pictures</summary>

Old Desktop
2020-07-25-plugin-available-icon-old
New Desktop
2020-07-25-plugin-available-icon-new
Old Mobile
2020-07-25-plugin-available-icon-mobile-old
New Mobile
2020-07-25-plugin-available-icon-mobile-new
</details>

### CODE REVIEW

**Comment by dkanada** [comment]
We should decide if we're going to add thumbnails first, because this won't work if we decide to keep the thumbnails.

**Comment by MrTimscampi** [comment]
> if we're going to add thumbnails first

I think those usually look tacky, but I know some vendors would probably want to make their plugin stand out in some way, plus it's more visual.

It's a tough choice. @jellyfin/core what do you think?

**Comment by dkanada** [comment]
I mentioned in chat that I'm fine with it on the condition that all plugins in the official repository get a nice icon that plays well with most of our themes.

**Comment by anthonylavado** [comment]
We do have a requirement to show logos in certain spots for a variety of the providers we use. We'll to figure out a way to do so. We can continue in chat or on the forums (https://forum.jellyfin.org/)

**Comment by Camc314** [comment]
> We should decide if we're going to add thumbnails first, because this won't work if we decide to keep the thumbnails.

One think that I think was discussed on the Matrix was replacing the folder icon with the plugin thumbnail. I think, if we have a huge plugin logo, it could very easily look tacky

**Comment by dkanada** [comment]
I think the plan for now is to add thumbnails, so this might want to wait until we turn the list view into a component that supports toggling between this and a card view or something.

**Comment by Camc314** [comment]
I'll close this for now, and redo it after thumbnails have been added

**Pull request closed without merging**
