### PR TITLE
Safari supports AC-3

### PR DESCRIPTION
**Pull request by Bond-009**
#703

### CODE REVIEW

**Comment by anthonylavado** [comment]
So I started on this (haven’t made the PR yet), but I stopped because I needed to figure something out. Does removing this check mean that it will test if support is available, and thus use it?

Are the checks just hard coded supported states?

**Comment by anthonylavado** [comment]
Okay, so the statement below does query correctly for support.

Want to remove the restriction on eac3 @bond-009? I’ve tested that it works as well, on both desktop and mobile Safari.

**Comment by Bond-009** [comment]
EAC-3 doesn't have the same restriction, right?
https://github.com/jellyfin/jellyfin-web/blob/361a6acc96d1d5b0cff926ceea4ce7e9d4ee9c6a/src/scripts/browserdeviceprofile.js#L83

**Comment by anthonylavado** [comment]
Yep all good ty @Bond-009

**Pull request merged**
