### PR TITLE
Fix missing port number in German translation

### PR DESCRIPTION
**Pull request by fritzmg**
See https://github.com/jellyfin/jellyfin-media-player/issues/288#issuecomment-1474852988

### CODE REVIEW

**Comment by fritzmg** [comment]
Ah, I just noticed that translations are managed here: https://translate.jellyfin.org/projects/jellyfin/jellyfin-web/
I am assuming this needs to be changed there instead?

**Comment by thornbill** [comment]
Yes that is right. Any translation changes should be made via weblate unless it is a change in the primary language file (en-us).

**Comment by fritzmg** [comment]
I submitted the change there (not sure if there is anything else to do, first time using weblate).

**Comment by thornbill** [comment]
There shouldn't be anything else you need to do. It should be automatically committed to master the next time it syncs over.

**Pull request closed without merging**
