### PR TITLE
Add no-cache attribute for fetch requests to /system/info/public to prevent stale server info

### PR DESCRIPTION
**Pull request by Doxterpepper**
**Changes**
- Changing caching policy for fetch calls to /System/Info/Public to avoid retrieving stale cached server info.

**Issues**

#5729

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
I think this should go to 10.9.
Could you please rebase and re-target the PR? For reference https://github.com/jellyfin/jellyfin-web/pull/5680#issuecomment-2156018605

**Comment by Doxterpepper** [comment]
Re targeted 1.9.z, but maybe it should go in both 1.9.z and master so it covers future releases?

**Comment by dmitrylyzo** [comment]
> Re targeted 1.9.z, but maybe it should go in both 1.9.z and master so it covers future releases?

It will be automatically backported to the `master` on release.

**Comment by thornbill** [comment]
It should be added as a header here also: https://github.com/jellyfin/jellyfin-web/blob/release-10.9.z/src/hooks/useSystemInfo.ts#L27

**Comment by fatexs** [comment]
I think this should be a blocker for any further release at this point. The amount if issues tracing back to this is crazy...

**Comment by thornbill** [comment]
1. We don't block other bug fixes being released because another bug has not been fixed yet.
2. I seriously doubt this will actually fix the majority of the "related" issues.

**Review by thornbill — APPROVED** [review]

**Pull request merged**
