### PR TITLE
Migration of display, home, playback and subtitles to ES6 modules and small fixes

### LINKED ISSUE #1359: Admin Dashboard and User Settings 'save' parity
When changes are made to the User Settings (playback, subtitles, display, etc.), changes are saved after leaving the page and refreshing, with no indication that changes have been made.

When changes are made on the Admin Dashboard, one presses the save button at the bottom of the page, is presented with a whirly loader thing, and a toast on the bottom left noting, "settings saved."

There's an inconsistency here that can be addressed by adding a 'save' button and a toast notification with its own position setting.

### PR DESCRIPTION
**Pull request by Influence365**
**Issues**
fixes #1359
part of #868

### CODE REVIEW

**Comment by Influence365** [comment]
I'm not sure whether to target master or es6 with this. If I should be targeting es6 let me know and I'll change it

**Comment by dkanada** [comment]
How does it solve those two issues?

**Comment by Influence365** [comment]
Firstly it adds a save button which was previously there just hidden.
And secondly it makes the toast notification appear when the save button is pressed

**Comment by dkanada** [comment]
Oh! I didn't notice those parameter changes, had no clue they existed. I'm in support of this change to keep everything uniform. The option to remove the toast and save button seems completely useless to me so we might even want to remove it at some point, but that's a discussion for later.

**Comment by Influence365** [comment]
yeah its such a minor change. It looks like to me there is a user setting with the option to remove the save button/notification which is a bit weird and I'm not quite sure why you would want to do it but its there.

One last thing, should this be targeting master or es6?

**Comment by dkanada** [comment]
That sounds like a good idea for now. It will force us to review these before merging anything else since we plan on merging es6 into master right after the next release which is very soon.

**Comment by Influence365** [comment]
So I'll leave as is targeting master? And possibly have it merged before 10.6?

**Comment by dkanada** [comment]
Regarding #1486 it looks like General already shows the toast, but I don't see where this will affect the Notifications page.

**Comment by dkanada** [comment]
I just tested this, and although the save button works, the autosave feature is still enabled. That would have to be removed before this could be merged.

**Comment by Influence365** [comment]
Thanks for noticing that. That should fix the issue of it autosaving the settings. I will remove #1486 from the description since, I am not addressing notifications here.

**Pull request merged**
