### PR TITLE
Replace existence check with optional chaining

### PR DESCRIPTION
**Pull request by prsantos-com**
**Changes**
Replaced the logical expression that checks for `null`/`undefined` with the optional chaining operator (`?.`) as per sonarcloud rule s6582.

**Issues**
<!-- Tag any issues that this PR solves here.
None

### CODE REVIEW

**Comment by prsantos-com** [comment]
Hi, just wondering if I need to do anything more to get this merged, otherwise I'll continue to wait.

**Review by thornbill — APPROVED** [review]

**Comment by thornbill** [comment]
> Hi, just wondering if I need to do anything more to get this merged, otherwise I'll continue to wait.

Hey @prsantos-com, no there isn't anything else that you need to do. I'm just a bit behind on reviews. As long as a PR doesn't have conflicts, I will get to it eventually. If you want to help things move faster, I would welcome your input in the form of reviews on other open PRs.

Thanks for your contribution!

**Comment by prsantos-com** [comment]
> Hey @prsantos-com, no there isn't anything else that you need to do. I'm just a bit behind on reviews. As long as a PR doesn't have conflicts, I will get to it eventually. If you want to help things move faster, I would welcome your input in the form of reviews on other open PRs.
> 
> Thanks for your contribution!

Hey @thornbill, I would be happy to review other open PRs. Which ones should I review first? Is there a particular way that I should go about doing this? I'm open to reading any guidelines specific to the project regarding PR reviews.

**Comment by thornbill** [comment]
I normally use this query to find PRs that are ready for review: https://github.com/jellyfin/jellyfin-web/pulls?q=is%3Apr+draft%3Afalse+-label%3Astale+-label%3A%22merge+conflict%22+-label%3Abackend+-label%3Ablocked+-label%3Aupstream+-label%3Adependencies+is%3Aopen

The main thing would be testing that the changes function as expected and there are not any obvious code errors being introduced. Thanks!

**Pull request merged**
