### PR TITLE
Add some tips for the enhanced NVDEC decoder

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- add some tips to prevent users from selecting it in general.

**Issues**
Fixes [#7508](https://github.com/jellyfin/jellyfin/issues/7508)

### CODE REVIEW

**Comment by nyanmisaka** [comment]
> Do we want this backported to 10.8 to prevent user errors?

Sure, but I can't add backport labels.

**Review by gardner — COMMENTED** [review]
This just exposes the setting in the UI. Is there code elsewhere that uses the setting?

**Comment by gardner** [comment]
The Spanish version of the text could be:

> Implementación experimental de NVDEC, no habilite esta opción a menos que encuentre errores de decodificación.

**Comment by nyanmisaka** [comment]
> This just exposes the setting in the UI. Is there code elsewhere that uses the setting?

It's used in the server side to switch between two NVDEC impl.

**Comment by nyanmisaka** [comment]
> The Spanish version of the text could be:
> 
> > Implementación experimental de NVDEC, no habilite esta opción a menos que encuentre errores de decodificación.

Thanks. You can also new translation via https://translate.jellyfin.org/

**Review by thornbill — APPROVED** [review]
These changes appear to be fine, but I noticed on my server the option appears to be enabled by default.

**Update:** I see it should be disabled by default. This may have just been some artifact from previous testing.

**Pull request merged**
