### PR TITLE
Migrate some easy components to ES6

### PR DESCRIPTION
**Pull request by Stampede10343**
Convert a few easy components to ES6 modules

**Changes**

`filedownloader`, `filesystem`, `keyboardnavigation` and `sanitizefilename`
coverted to ES6 modules.

**Issues**

Part of #868.

### CODE REVIEW

**Comment by Stampede10343** [comment]
> For bigger files, you can keep the indentation as-is and disable the ESLint indentation rule with `/* eslint-disable indent */`. It makes it easier for us to review (Otherwise, Git gets tripped up when looking for changes)

Yeah I didn't realize that until later, I'll keep it in mind for the future.

**Comment by dkanada** [comment]
> for bigger files

Actually, all files would be ideal :smile: it really helps speed up reviews for the ES6 migration.

**Comment by dkanada** [comment]
Of course this pull request is fine though.

**Comment by KristupasSavickas** [comment]
> For bigger files, you can keep the indentation as-is and disable the ESLint indentation rule with `/* eslint-disable indent */`. It makes it easier for us to review (Otherwise, Git gets tripped up when looking for changes)

You can set "Hide whitespace changes" in github PR view to aid this issue :)

**Pull request merged**
