### PR TITLE
Add Fullscreen Ability to Books

### PR DESCRIPTION
**Pull request by shortspider**
**Changes**

Add the ability to full screen books. This is important for mobile as it will give the book more space and allow the screen to stay on.

**Issues**

### CODE REVIEW

**Comment by shortspider** [comment]
Hey will this be reviewed or did I miss some step in the process?

**Comment by thornbill** [comment]
@shortspider you didn’t miss any steps. This will be reviewed sometime. It’s just a bit slow moving around here right now. 🐢

**Comment by shortspider** [comment]
@thornbill OK no problem, just wanted to make sure I didn't do something wrong!

**Comment by shortspider** [comment]
@thornbill not trying to nag but is it possible to get this reviewed? No activity on it for 15 days and it looks like there was at least one release since this was opened.

Happy to do whatever I can to help move this along.

**Comment by thornbill** [comment]
Sorry @shortspider things are just moving slowly here right now. I’m sure someone will review it in time for 10.8 though.

**Review by thornbill — APPROVED** [review]

**Pull request merged**
