### PR TITLE
Import Translations

### PR DESCRIPTION
**Pull request by joshuaboniface**
Do not merge until final release.

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Sorry for the force-push, accidentally rebased this (unmerged) PR instead of the main repo one.

**Comment by LeoVerto** [comment]
Is this PR going to be squashed? Or would that break Weblate?

**Comment by joshuaboniface** [comment]
@LeoVerto It will likely not break Weblate, but I'd also like to see each translation commit kept to ensure credit where credit is due.

**Comment by joshuaboniface** [comment]
Confirmed translations up-to-date; merging for release.

**Pull request merged**
